### ISSUE TITLE
ProtocolSupport crashes

### ISSUE THREAD

**Issue by mio-19** [GlowstoneMC/Glowstone#1078]
ProtocolSupport version: https://protocol.support/old/unsupported/ymmv/ProtocolSupport-1.12.2.jar
log:
```
java.lang.NoClassDefFoundError: net/glowstone/net/protocol/ProtocolType
	at protocolsupport.zplatform.impl.glowstone.GlowStonePacketFactory.getInHandshakeStartPacketId(GlowStonePacketFactory.java:732)
	at protocolsupport.protocol.packet.ServerBoundPacket.<clinit>(ServerBoundPacket.java:7)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:99)
	at net.glowstone.GlowServer.loadPlugins(GlowServer.java:1251)
	at net.glowstone.GlowServer.start(GlowServer.java:770)
	at net.glowstone.GlowServer.run(GlowServer.java:625)
	at net.glowstone.GlowServer.main(GlowServer.java:489)
Caused by: java.lang.ClassNotFoundException: net.glowstone.net.protocol.ProtocolType
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 9 more
```

**Comment by mastercoms** [comment]
https://github.com/GlowstoneMC/Glowstone/commit/b3b6502f64772bdde3d397c29e5d4d0386c06836#diff-f17bb93483efb2ef59a7b7a9a67c0867R1

The symbol was changed here. ProtocolSupport should be updated to use the new class. As I understand it, ProcotolSupport has dropped support for Glowstone because it is still on 1.12. Therefore, you will have to fork ProtocolSupport and add support for it. If they still support Glowstone, then ask them to update the class used.
