### ISSUE TITLE
WorldEdit support

### ISSUE THREAD

**Issue by mio-19** [GlowstoneMC/Glowstone#1079]
Glowstone is missing `boolean org.bukkit.Material.isLegacy()`

log:
```
00:04:03 [INFO] Enabling WorldEdit v7.1.0-SNAPSHOT;4822-a27ade5
00:04:03 [SEVERE] Plugin WorldEdit v7.1.0-SNAPSHOT;4822-a27ade5 has failed to register events for class com.sk89q.worldedit.bukkit.WorldEditListener because org/bukkit/event/player/PlayerCommandSendEvent does not exist.
00:04:03 [SEVERE] Error occurred while enabling WorldEdit v7.1.0-SNAPSHOT;4822-a27ade5 (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean org.bukkit.Material.isLegacy()'
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.initializeRegistries(WorldEditPlugin.java:183)
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:143)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
	at net.glowstone.GlowServer.enablePlugins(GlowServer.java:1346)
	at net.glowstone.GlowServer.start(GlowServer.java:771)
	at net.glowstone.GlowServer.run(GlowServer.java:625)
	at net.glowstone.GlowServer.main(GlowServer.java:489)
```

**Comment by mastercoms** [comment]
This is because WorldEdit 7.1.0 is for 1.13 and above. Please use 6.1.9.
