### ISSUE TITLE
Crash when trying to start Glowstone++ for the first time

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#108]
I don't exactly know what happened... Running on Lubuntu 14.04(I think)

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/glowstone/GlowServer : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by TekkitCommando** [comment]
You have a lower Java version then what's accepted

**Comment by TekkitCommando** [comment]
Please update your Java :)

**Comment by codekilla747** [comment]
Thank you, didn't pay attention to that.

**Comment by codekilla747** [comment]
@TekkitCommando Is there a certain version of java that is required? I used
```
sudo apt-get install openjdk-7-jre
```
and I still get the error when trying to run the server.

**Comment by Castar** [comment]
you must use java 8. sudo apt-get install openjdk-8-jre

**Comment by codekilla747** [comment]
@Castar when i run that it outputs:
```
blake@http-02:~/serverMC$ sudo apt-get install openjdk-8-jre
[sudo] password for blake: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package openjdk-8-jre
```

**Comment by TekkitCommando** [comment]
@codekilla747 idk I've not used Linux cmd line much.

**Comment by TekkitCommando** [comment]
@mastercoms or @phillmac may know if it's another command. Phillmac knows quite a bit about Ubuntu and has a lot of machines running it

**Comment by ExpandingDev** [comment]
I don't think that Linux has the latest JRE version in its package
repositories, but someone else has already made instructions on how to
install JRE8 for Linux manually:
http://tecadmin.net/install-oracle-java-8-jdk-8-ubuntu-via-ppa/#

**Comment by codekilla747** [comment]
@ExpandingDev That worked! Thank you

**Comment by mastercoms** [comment]
Here is the article from the creators of the ppa: http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html

**Comment by phillmac** [comment]
ppa is the best way imho
