### ISSUE TITLE
"Shop - a simple, intuitive shop plugin" Support

### ISSUE THREAD

**Issue by mio-19** [GlowstoneMC/Glowstone#1080]
plugin: https://www.spigotmc.org/resources/shop-a-simple-intuitive-shop-plugin.9628/
logs:
```
01:19:33 [INFO] Enabling Shop v1.8.1
01:19:34 [SEVERE] Error occurred while enabling Shop v1.8.1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData
	at com.snowgears.shop.Shop.onEnable(Shop.java)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
	at net.glowstone.GlowServer.enablePlugins(GlowServer.java:1346)
	at net.glowstone.GlowServer.start(GlowServer.java:819)
	at net.glowstone.GlowServer.run(GlowServer.java:625)
	at net.glowstone.GlowServer.main(GlowServer.java:489)
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.data.BlockData
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 8 more
01:19:34 [INFO] Disabling Shop v1.8.1
```

**Comment by mastercoms** [comment]
BlockData is in 1.13 and above. Please use an older version of this plugin.
