### ISSUE TITLE
Spigot-inspired /timings doesn't work.

### ISSUE THREAD

**Issue by HyperPlay** [GlowstoneMC/Glowstone#109]
<code>18:53:00 [SEVERE] Exception while executing command: /timings report
org.bukkit.command.CommandException: Unhandled exception executing 'timings report' in org.bukkit.command.defaults.TimingsCommand(timings)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:191)
    at net.glowstone.GlowServer.dispatchCommand(GlowServer.java:1147)
    at net.glowstone.entity.GlowPlayer$2.run(GlowPlayer.java:1573)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.glowstone.scheduler.GlowTask.run(GlowTask.java:163)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:181)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:110)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.bukkit.command.defaults.TimingsCommand.executeSpigotTimings(TimingsCommand.java:87)
    at org.bukkit.command.defaults.TimingsCommand.execute(TimingsCommand.java:116)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:184)
    ... 15 more</code>

I am getting this error when using <code>/timings paste</code> and <code>/timings report</code>.
##

**Comment by mastercoms** [comment]
Timings and I think some other spigot altered/created commands don't work. I'll work on them once I find the time.

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/GlowstonePlusPlus/commit/c8489172ed670cfec8f852c7ad366ad26ee3350c.

http://timings.aikar.co/v2/?id=64a85be7f7cd44d9899c6f094344bd47&raw=1
http://timings.aikar.co/v2/?id=64a85be7f7cd44d9899c6f094344bd47
