### ISSUE TITLE
Switching lever on and off caused this

### ISSUE THREAD

**Issue by DefinitlyEvil** [GlowstoneMC/Glowstone#110]
```
java.lang.ArrayIndexOutOfBoundsException: 226
        at java.util.LinkedList.toArray(LinkedList.java:1053)
        at java.util.ArrayList.<init>(ArrayList.java:177)
        at net.glowstone.entity.GlowPlayer.processBlockChanges(GlowPlayer.java:537)
        at net.glowstone.entity.GlowPlayer.pulse(GlowPlayer.java:486)
        at net.glowstone.GlowWorld.pulse(GlowWorld.java:499)
        at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:48)
01:03:48 [ERROR] Error occurred while pulsing world world
java.lang.ArrayIndexOutOfBoundsException: 299
        at java.util.LinkedList.toArray(LinkedList.java:1053)
        at java.util.ArrayList.<init>(ArrayList.java:177)
        at net.glowstone.entity.GlowPlayer.processBlockChanges(GlowPlayer.java:537)
        at net.glowstone.entity.GlowPlayer.pulse(GlowPlayer.java:486)
        at net.glowstone.GlowWorld.pulse(GlowWorld.java:499)
        at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:48)
01:03:48 [ERROR] Error occurred while pulsing world world
java.lang.ArrayIndexOutOfBoundsException: 370
        at java.util.LinkedList.toArray(LinkedList.java:1053)
        at java.util.ArrayList.<init>(ArrayList.java:177)
        at net.glowstone.entity.GlowPlayer.processBlockChanges(GlowPlayer.java:537)
        at net.glowstone.entity.GlowPlayer.pulse(GlowPlayer.java:486)
        at net.glowstone.GlowWorld.pulse(GlowWorld.java:499)
        at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:48)
01:03:49 [ERROR] Error occurred while pulsing world world
java.lang.ArrayIndexOutOfBoundsException: 441
        at java.util.LinkedList.toArray(LinkedList.java:1053)
        at java.util.ArrayList.<init>(ArrayList.java:177)
        at net.glowstone.entity.GlowPlayer.processBlockChanges(GlowPlayer.java:537)
        at net.glowstone.entity.GlowPlayer.pulse(GlowPlayer.java:486)
        at net.glowstone.GlowWorld.pulse(GlowWorld.java:499)
        at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:48)
```

**Comment by MOMOTHEREAL** [comment]
Going to look into this now.

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/4f4b27b439ff521b7132abe1e93706a21971b630
