### ISSUE TITLE
unable to generate chunks 

### ISSUE THREAD

**Issue by 2019Z2** [GlowstoneMC/Glowstone#1124]
Glowstone build: 2021.7.0 

when loading worlds , several chunks cannot be loaded on prebuilt maps (downloaded maps from the internet:
https://www.planetminecraft.com/project/hogwarts-2883086/ (the map I used)) either by loading it directly on the server, or by loading the world first in a minecraft client, loading it on a server, editing it by placing paintings' 
 and reloading the server.

i expected to be able to walk to the chunks that has been edited, but they disappeared.
it started to getting worse after reloading the server, i was simply unable to join the server. perhaps the server couldn't generate the chunk i stayed on .

this issue occurred only on this build. on earlier builds, i could've edit the chunks without any problems,  and they would still be generated properly.

the steps to reproduce the issue: 
1. download the map (link provided above)
2. start the server (then, some chunks will be missing near spawn)
alternatively, you can also:
1. download the map
2. load the world in minecraft 1.12
3. load the world into the server
4. edit several chunks in game (i placed paintings)
5. reload the server (NOTICE: you should leave those chunks before reloading the server, as you might not be able to join, or you'll spawn in the void , the chunks might disappear)

the code in the console: 15:37:22 [SEVERE] Error while generating chunk (-131,25)
java.lang.NullPointerException
	at net.glowstone.chunk.ChunkManager.getBiomeGridAtLowerRes(ChunkManager.java:417)
	at net.glowstone.generator.OverworldGenerator.generateTerrainDensity(OverworldGenerator.java:501)
	at net.glowstone.generator.OverworldGenerator.generateRawTerrain(OverworldGenerator.java:385)
	at net.glowstone.generator.OverworldGenerator.generateChunkData(OverworldGenerator.java:278)
	at net.glowstone.chunk.ChunkManager.generateChunk(ChunkManager.java:275)
	at net.glowstone.chunk.ChunkManager.loadChunk(ChunkManager.java:169)
	at net.glowstone.chunk.GlowChunk.load(GlowChunk.java:224)
	at net.glowstone.chunk.GlowChunk.load(GlowChunk.java:219)
	at net.glowstone.chunk.GlowChunk.getSection(GlowChunk.java:401)
	at net.glowstone.chunk.GlowChunk.getType(GlowChunk.java:432)
	at net.glowstone.block.GlowBlock.getTypeIdNoCache(GlowBlock.java:190)
	at net.glowstone.block.GlowBlock.getType(GlowBlock.java:180)
	at net.glowstone.block.blocktype.BlockMycel.updateBlock(BlockMycel.java:52)
	at net.glowstone.GlowWorld.updateBlocksInSection(GlowWorld.java:558)
	at net.glowstone.GlowWorld.updateBlocksInActiveChunks(GlowWorld.java:540)
	at net.glowstone.GlowWorld.pulse(GlowWorld.java:487)
	at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:170)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------------------------------
End of lecture
---------------------------------------------------------------------------
unfortunately, I don't speak english natively, so if you'll experience issues with understanding the contents above , i also added the contents in hebrew, for your convenience.
----------------------------------------------------------------------------  
להלן תוכן הפנייה בעברית
גירסא: 2021.7.0
 תוכן הפניה: עולמות שהורדו מהמרשתת (אינטרנט, הקישור למעלה) לא נטענו כראוי. , וכעת, חסרים בהם צ׳אנקים.

כיצד זה קרה: לאחר התקנת העולם (קישור למעלה) וטעינת השרת, גיליתי שחסריפ צ׳אנקים. למעשה, העולם היה מחורר כולו כגבינה בצ׳אנקים חסרים.
כדי להתגבר על הבעיה, ראשית, טענתי את העולם בקליינט של מיינקראפט 1.12,  והתקנתי את העולם בשרת. נראה שהתגברתי על הבעיה, אך כשערכתי את העולם (שמתי כמה תמונות), העולם שוב התקלקל, וצ׳אנקים מסוימים נעלמו .
ניסיתי לבדוק אם הבעיה עדיין מתרחשת ע״י טעינה מחדש של העולם , וגיליתי שאני לא יכול להתחבר אליו, כנראה הצ׳אנקים שעמדתי עליהם נעלמו גם הם, והמשחק לא יודע מה לעשות.

מה היה אמור לקרות: העולם לא היה אמור להתקלקל, והשרת היה אמור לטעון את הצ׳אנקים שלא נטענו כמצופה.
כיצד לבצע שנית את התקלה :ֿ
יש להתקין את הגירסא שמצויינת לעיל מן האתר, ןלטעון את  השרת.1
למחוק את המפה שנוצרה, 
ולהתקין את המפה שהורדה מהמרשתת.3
4. להתחבר לשרת.
או:
1. לבצע את שלבים 1, ו2
2. לטעון את העולם בקליינט של מיינקראפט 1.12
3. להתקין את המפה לאחר שנטענה
4. לשים כמה בלוקים (למשל: תמונות)
5. לטעון מחדש את העולם

עדכון: כמדומני, השרת טען צ׳אנקים בלי בעיות בעדכונים קודמים.

יש פירוט של הקוד שהופיע בקונסולה למעלה.

----------------------------------------------------------------------------
סוף

----------------------------------------------------------------------------

**Comment by mastercoms** [comment]
Hi, thank you for the report! Is this on the latest build or the release build? If it is the release build, could you please test it on the latest build?

**Comment by 2019Z2** [comment]
I'm not sure if I used the release build,  or the latest build.
Pretty sure I used the release build 2021.7.0.
Anyway, I'll test  it, but it'll take me quite long time to do so, as I'm using ssh.

**Comment by mastercoms** [comment]
Alright, I can look into it soon.

**Comment by 2019Z2** [comment]
so, it's time for an update:
the same issue still occurs in the latest release 2021.8.0.

**Comment by 2019Z2** [comment]
> so, it's time for an update:
> the same issue still occurs in the latest release 2021.8.0.

i'll try the dev branch

**Comment by 2019Z2** [comment]
> > so, it's time for an update:
> > the same issue still occurs in the latest release 2021.8.0.
> 
> i'll try the dev branch

didn't worked 
SEVERE: Error during server startup.
java.lang.ExceptionInInitializerError
	at com.destroystokyo.paper.MaterialTags.<clinit>(MaterialTags.java:525)
	at net.glowstone.block.entity.state.GlowDispenser.register(GlowDispenser.java:84)
	at net.glowstone.GlowServer.createFromArguments(GlowServer.java:580)
	at net.glowstone.GlowServer.main(GlowServer.java:542)
Caused by: java.lang.NullPointerException
	at org.bukkit.Bukkit.getTag(Bukkit.java:1770)
	at org.bukkit.Tag.<clinit>(Tag.java:28)
	... 4 more
