### ISSUE TITLE
Java 17 & ASM9 support for Glowstone (and Linkstone)

### ISSUE THREAD

**Issue by 0utplay** [GlowstoneMC/Glowstone#1141]
Hello, I noticed that the Glowstone dev branch is supporting Minecraft 1.19. I've tried using Java 17 as it is the current LTS  but stumbled over some problems with ASM6.
Do you consider updating ASM6 to ASM9 and therefore support Java 17+?

**Comment by mastercoms** [comment]
Is this specific to Linkstone? I'm not sure if I had any issues running Glowstone itself on Java 17.

**Comment by 0utplay** [comment]
```
2022/08/13 15:46:46 [SCHWERWIEGEND] Error during server startup.
java.lang.UnsupportedOperationException: Module requires ASM6
	at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:144)
	at org.objectweb.asm.ClassReader.readModuleAttributes(ClassReader.java:781)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:580)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at net.glowstone.GlowPluginTypeDetector.scanFile(GlowPluginTypeDetector.java:97)
	at net.glowstone.GlowPluginTypeDetector.scan(GlowPluginTypeDetector.java:46)
	at net.glowstone.GlowServer.loadPlugins(GlowServer.java:1249)
	at net.glowstone.GlowServer.start(GlowServer.java:780)
	at net.glowstone.GlowServer.run(GlowServer.java:635)
	at net.glowstone.GlowServer.main(GlowServer.java:499)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at eu.cloudnetservice.wrapper.Wrapper.lambda$startApplication$1(Wrapper.java:465)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
Thats what I get when starting

**Comment by GeorgeV220** [comment]
I have the same issue with the latest dev build

**Comment by GeorgeV220** [comment]
Why is the issue reopened?
