### ISSUE TITLE
Error while loading chunk; Invalid tag type: 12

### ISSUE THREAD

**Issue by cd-FileX** [GlowstoneMC/Glowstone#1144]
Title: **Invalid tag on minecraft world (1.16)**

Glowstone build: `2021.8.0`

When inserting a world into the `worlds` folder played in minecraft (1.16) originally, the following error occurs:
<details>

```[SEVERE] Error while loading chunk (16,6)
java.io.IOException: Invalid tag type: 12
        at net.glowstone.util.nbt.TagType.byIdOrError(TagType.java:52)
        at net.glowstone.util.nbt.NbtInputStream.readCompound(NbtInputStream.java:87)
        at net.glowstone.util.nbt.NbtInputStream.readTagPayload(NbtInputStream.java:176)
        at net.glowstone.util.nbt.NbtInputStream.readTagPayload(NbtInputStream.java:169)
        at net.glowstone.util.nbt.NbtInputStream.readCompound(NbtInputStream.java:97)
        at net.glowstone.util.nbt.NbtInputStream.readTagPayload(NbtInputStream.java:176)
        at net.glowstone.util.nbt.NbtInputStream.readCompound(NbtInputStream.java:97)
        at net.glowstone.util.nbt.NbtInputStream.readTagPayload(NbtInputStream.java:176)
        at net.glowstone.util.nbt.NbtInputStream.readCompound(NbtInputStream.java:79)
        at net.glowstone.util.nbt.NbtInputStream.readCompound(NbtInputStream.java:57)
        at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:66)
        at net.glowstone.chunk.ChunkManager.loadChunk(ChunkManager.java:167)
        at net.glowstone.chunk.GlowChunk.load(GlowChunk.java:232)
        at net.glowstone.generator.populators.StructurePopulator.populate(StructurePopulator.java:36)
        at net.glowstone.chunk.ChunkManager.populateChunk(ChunkManager.java:257)
        at net.glowstone.chunk.ChunkManager.forcePopulation(ChunkManager.java:272)
        at net.glowstone.GlowWorld.prepareSpawn(GlowWorld.java:976)
        at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:948)
        at net.glowstone.GlowWorld.<init>(GlowWorld.java:441)
        at net.glowstone.GlowServer.createWorld(GlowServer.java:2311)
        at net.glowstone.GlowServer.start(GlowServer.java:809)
        at net.glowstone.GlowServer.run(GlowServer.java:635)
        at net.glowstone.GlowServer.main(GlowServer.java:499)
```
</details> 

To reproduce the exact same scenario:
- "Install" 2021.8.0 on linux with openjdk 1.8.0_402
- Download [this world](https://help.datblock.com/#/downloads?id=datearth-polis-world-dec-27-2023) and put it's peaces together with the following command: <details>`cat datblock-datearth-polis-world-dec-27-2023.zip.001 datblock-datearth-polis-world-dec-27-2023.zip.002 datblock-datearth-polis-world-dec-27-2023.zip.003 datblock-datearth-polis-world-dec-27-2023.zip.004 datblock-datearth-polis-world-dec-27-2023.zip.005 datblock-datearth-polis-world-dec-27-2023.zip.006 datblock-datearth-polis-world-dec-27-2023.zip.007 datblock-datearth-polis-world-dec-27-2023.zip.008 datblock-datearth-polis-world-dec-27-2023.zip.009 datblock-datearth-polis-world-dec-27-2023.zip.010 datblock-datearth-polis-world-dec-27-2023.zip.011 datblock-datearth-polis-world-dec-27-2023.zip.012 datblock-datearth-polis-world-dec-27-2023.zip.013 datblock-datearth-polis-world-dec-27-2023.zip.014 datblock-datearth-polis-world-dec-27-2023.zip.015 datblock-datearth-polis-world-dec-27-2023.zip.016 datblock-datearth-polis-world-dec-27-2023.zip.017 datblock-datearth-polis-world-dec-27-2023.zip.018 datblock-datearth-polis-world-dec-27-2023.zip.019 datblock-datearth-polis-world-dec-27-2023.zip.020 datblock-datearth-polis-world-dec-27-2023.zip.021 datblock-datearth-polis-world-dec-27-2023.zip.022 datblock-datearth-polis-world-dec-27-2023.zip.023 datblock-datearth-polis-world-dec-27-2023.zip.024 datblock-datearth-polis-world-dec-27-2023.zip.025 datblock-datearth-polis-world-dec-27-2023.zip.026 datblock-datearth-polis-world-dec-27-2023.zip.027 > datblock-datearth.zip`</details>
- Extract it into `/worlds/world`
- Run glowstone

(Just for ensurance; is this project still maintained? Would be sad if not.. (I can't really program Java though if I could help something I would do so))

**Comment by mastercoms** [comment]
1.16 is not supported right now. We are working on upgrading the project to past 1.12 but it's introduced a big wall to momentum.

**Comment by cd-FileX** [comment]
I see. Guess that's the problem.
So, the project is still in active development, just behind the scenes?
If that's the case, as I can't really program java I would maybe like to help with the documentation

**Comment by mastercoms** [comment]
Thank you for the offer! It's quite slow right now, there's lots of hard problems, and once we solve those, we can think about documentation and we'll let you know if you're interested 🙌

**Comment by cd-FileX** [comment]
Alright.
Then good luck and try your best

**Comment by mastercoms** [comment]
I'm going to close this issue because it seems solved in the dev branch (tag type 12, long array is implemented).
