### ISSUE TITLE
Entities don't despawn after killing them

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#156]
**Java version**: `build 1.8.0_66-b17`
**OS**: `Mac OSX El Capitan (10.11)`
**Glowstone ver.**: `newest (40df0c7)`

**What I did**:
I got a spawn egg from the creative menu then switched to survival and killed it with a diamond sword (I also got that from the creative menu) then after hitting it (I saw the red indicating that I hit it) then I kept hitting it and red didn't show up (I killed it) but the entity didn't despawn.

**EDIT**: I got a stack trace when glowstone tried to save the entity here it is:

```
08:16:39 [WARNING] Error saving GlowVillager in GlowChunk{world=world,x=-1,z=-4}
java.lang.NullPointerException
    at net.glowstone.io.entity.VillagerStore.save(VillagerStore.java:23)
    at net.glowstone.io.entity.VillagerStore.save(VillagerStore.java:7)
    at net.glowstone.io.entity.EntityStorage.save(EntityStorage.java:165)
    at net.glowstone.io.anvil.AnvilChunkIoService.write(AnvilChunkIoService.java:212)
    at net.glowstone.ChunkManager.performSave(ChunkManager.java:379)
    at net.glowstone.GlowWorld.lambda$save$0(GlowWorld.java:979)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.glowstone.scheduler.GlowTask.run(GlowTask.java:163)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by twizmwazin** [comment]
I actually have this fixed in a local branch. I'll clean it up and PR it.

**Comment by mastercoms** [comment]
ok, thanks!
