### ISSUE TITLE
Dependency relocation?

### ISSUE THREAD

**Issue by Paulomart** [GlowstoneMC/Glowstone#167]
Hi,
just wannted to ask if you plan to do that?

**Comment by gdude2002** [comment]
Can you elaborate a bit on that? What exactly are you referring to?

**Comment by Paulomart** [comment]
Sure: I mean CraftBukkit was moving libs into org.bukkit.craftbukkit.libs.*. I have a wirtten a wrapper for spigot that uses a ClassPath hack to inject some libs, but its messing up because im using flowpower in one of my projects too (Its not loaded by the pluginloader). Because of that I have issues with the networking in glowstone itself, probably because they are different versions. My solution to solve this, that Im relocation flowpowered and netty into net.glowstone.lib

**Comment by gdude2002** [comment]
Well, base Glowstone had an entire library system that downloaded and injected libraries for you. I'm not sure if GS++ has that or not - best ping @mastercoms

**Comment by Paulomart** [comment]
I know that, I think it is still in. But I want to keep Spigot support.

**Comment by kamcio96** [comment]
Spigot 1.8+ has normal dependency. eg: io.netty

**Comment by Paulomart** [comment]
Okey then, but why breaks g++ and spigot dosent?

**Comment by kamcio96** [comment]
what class do you use?

**Comment by Paulomart** [comment]
Its runtime issue, Im getting a stacktrace, one sec

**Comment by Paulomart** [comment]
I wore getting this, but in fact Im not able to reprodruce now Oo:
```
[SCHWERWIEGEND] Error in network input
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1171)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:571)
	at com.flowpowered.networking.util.ByteBufUtils.readVarInt(ByteBufUtils.java:79)
	at net.glowstone.net.codec.handshake.HandshakeCodec.decode(HandshakeCodec.java:13)
	at net.glowstone.net.codec.handshake.HandshakeCodec.decode(HandshakeCodec.java:10)
	at net.glowstone.net.pipeline.CodecsHandler.decode(CodecsHandler.java:53)
	at net.glowstone.net.pipeline.CodecsHandler.decode(CodecsHandler.java:19)
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	... 16 more
```

**Comment by gdude2002** [comment]
Heisenbug! Always fun.

What were you patching in? Flow-networking? Why?

**Comment by Paulomart** [comment]
Yes, flow-networking, Im using it for my backend networking

**Comment by gdude2002** [comment]
Is there some reason our fork isn't suitable?

**Comment by Paulomart** [comment]
I guess, I could take a look at it, its just update to Netty 5?

**Comment by gdude2002** [comment]
Yup, that's about it.

**Comment by Paulomart** [comment]
Okey sweet. I will look at it if it breaks, now it seems to be working?

**Comment by Paulomart** [comment]
Still wanna discuess relocation?

**Comment by gdude2002** [comment]
Up to you, really. If you think it would be helpful for the project, pitch away :P

**Comment by kamcio96** [comment]
It isn't about relocation xD
If you are using maven you can easily relocate your dependencies to

your.plugin.package.lib.com.flowpowered.networking

**Comment by gdude2002** [comment]
Oh, that's right, I'd forgotten about that. Jarjar is good for that if you're stuck for tools.

**Comment by Paulomart** [comment]
jear @kamcio96 is right, the plugin/wrapper would have to do that, closing than. Thanks all :)
