### ISSUE TITLE
Cannot dig multiple blocks in less then one tick?

### ISSUE THREAD

**Issue by Paulomart** [GlowstoneMC/Glowstone#169]
If you spam click on two tall_grass to destroy it, you destroy both but get this exception:

```
2016/01/24 12:29:53 [SCHWERWIEGEND] Error while handling DiggingMessage(state=1, x=56, y=4095, z=22, face=0) (handler: DiggingHandler)
java.lang.NullPointerException
    at net.glowstone.net.handler.play.player.DiggingHandler.handle(DiggingHandler.java:129)
    at net.glowstone.net.handler.play.player.DiggingHandler.handle(DiggingHandler.java:26)
    at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
    at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
    at net.glowstone.net.GlowSession.pulse(GlowSession.java:428)
    at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:173)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:110)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

```

**Comment by gdude2002** [comment]
I believe @mastercoms is already looking at this one, thanks for the extra info though
