### ISSUE TITLE
Query service: Error in query handling io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1

### ISSUE THREAD

**Issue by deathcap** [GlowstoneMC/Glowstone#187]
Query client requests cause Glowstone++ to log "Error in query handling" errors

To test, edit config/glowstone.yml set query-enabled: true, query-port: 25565
Use a query tool, tried both https://github.com/xPaw/PHP-Minecraft-Query/blob/master/README.md#query and https://github.com/deathcap/node-minecraft-ping with the same error:

```
Glowstone++ $ java -mx2G -jar archive/glowstone++-1.8.7-SNAPSHOT-632.jar 
17:10:56 [INFO] This server is running Glowstone++ version null (Implementing API version null)
17:10:57 [INFO] Recipes: 295 shaped, 63 shapeless, 24 furnace, 10 dynamic, 14 fuels.
17:10:57 [WARNING] The server is running in offline mode! Only do this if you know what you're doing.
17:10:57 [INFO] Scanning plugins...
17:10:57 [INFO] Preparing spawn for world...
17:10:57 [INFO] Preparing spawn for world: done
17:10:57 [INFO] Preparing spawn for world_nether...
17:10:58 [INFO] Preparing spawn for world_nether: done
17:10:58 [INFO] Preparing spawn for world_the_end...
17:10:58 [INFO] Preparing spawn for world_the_end: done
17:10:58 [INFO] Binding to address: 0.0.0.0/0.0.0.0:2556...
17:10:58 [INFO] Successfully bound to: /0:0:0:0:0:0:0:0:2556
17:10:58 [INFO] Binding query to address: 0.0.0.0/0.0.0.0:25565...
17:10:58 [INFO] Ready for connections.
17:11:10 [SEVERE] Error in query handling
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
    at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:111)
    at io.netty.buffer.WrappedByteBuf.release(WrappedByteBuf.java:832)
    at io.netty.buffer.SimpleLeakAwareByteBuf.release(SimpleLeakAwareByteBuf.java:44)
    at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:84)
    at io.netty.channel.DefaultAddressedEnvelope.release(DefaultAddressedEnvelope.java:97)
    at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:84)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:112)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:389)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:956)
    at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
    at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280)
    at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877)
    at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706)
    at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661)
    at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126)
17:11:10 [WARNING] Failed to release a message: DatagramPacket(=> /0:0:0:0:0:0:0:1:49497, PooledUnsafeDirectByteBuf(freed))
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
    at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:111)
    at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:84)
    at io.netty.channel.DefaultAddressedEnvelope.release(DefaultAddressedEnvelope.java:97)
    at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:84)
    at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:109)
    at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:288)
    at io.netty.channel.ChannelOutboundBuffer.failFlushed(ChannelOutboundBuffer.java:589)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:839)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:298)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:806)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1283)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:166)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:355)
    at io.netty.channel.PausableChannelEventExecutor.invokeFlush(PausableChannelEventExecutor.java:46)
    at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:546)
    at net.glowstone.net.query.QueryHandler.channelReadComplete(QueryHandler.java:50)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadCompleteNow(ChannelHandlerInvokerUtil.java:92)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelReadComplete(DefaultChannelHandlerInvoker.java:167)
    at io.netty.channel.PausableChannelEventExecutor.invokeChannelReadComplete(PausableChannelEventExecutor.java:91)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:412)
    at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:962)
    at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
    at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280)
    at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877)
    at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706)
    at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661)
    at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126)
```

Tested builds 632 and 471, no difference. Not sure if this is a Glowstone++ regression from Glowstone. References:
- https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/tree/master/src/main/java/net/glowstone/net/query
- https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/e854d5056259450a0836fae220fd83d60bb75b48 Added query support
- https://github.com/GlowstoneMC/Glowstone/issues/377 Query support
- http://wiki.vg/Query 

Note: query service is distinct from pings (modern or legacy https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/issues/186)

**Comment by mastercoms** [comment]
https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/fb5328065f67f859870088e7bcb0c0e5a1918799#commitcomment-12240746
