### ISSUE TITLE
Chunk unknown version

### ISSUE THREAD

**Issue by Paulomart** [GlowstoneMC/Glowstone#199]
```
2016/02/13 19:57:07 [SCHWERWIEGEND] Error while loading chunk (-16,8)
java.io.IOException: Unknown version: 0
    at net.glowstone.io.anvil.RegionFile.getChunkDataInputStream(RegionFile.java:211)
    at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:62)
    at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:132)
    at net.glowstone.GlowChunk.load(GlowChunk.java:265)
    at net.glowstone.GlowChunk.load(GlowChunk.java:260)
    at net.glowstone.GlowChunk.getSection(GlowChunk.java:359)
    at net.glowstone.GlowChunk.getType(GlowChunk.java:394)
    at net.glowstone.block.GlowBlock.getTypeId(GlowBlock.java:195)
    at net.glowstone.block.GlowBlock.getType(GlowBlock.java:190)
    at net.glowstone.block.blocktype.BlockLiquid.calculateTarget(BlockLiquid.java:114)
    at net.glowstone.block.blocktype.BlockLiquid.calculateFlow(BlockLiquid.java:95)
    at net.glowstone.block.blocktype.BlockLiquid.updatePhysics(BlockLiquid.java:201)
    at net.glowstone.block.blocktype.BlockLiquid.receivePulse(BlockLiquid.java:67)
    at net.glowstone.GlowWorld.pulseTickMap(GlowWorld.java:1797)
    at net.glowstone.GlowWorld.pulse(GlowWorld.java:382)
    at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:52)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```
##

**Comment by Paulomart** [comment]
Could this happen, because the world was generated using a Spigot server?

**Comment by Paulomart** [comment]
Getting this one too:
```
2016/02/15 19:51:57 [SCHWERWIEGEND] Error while loading chunk (7,-6)
java.io.IOException: Invalid length: 104495105 > 4096
	at net.glowstone.io.anvil.RegionFile.getChunkDataInputStream(RegionFile.java:197)
	at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:62)
	at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:132)
	at net.glowstone.GlowChunk.load(GlowChunk.java:265)
	at net.glowstone.GlowChunk.load(GlowChunk.java:260)
	at net.glowstone.GlowChunk.getSection(GlowChunk.java:359)
	at net.glowstone.GlowChunk.getType(GlowChunk.java:394)
	at net.glowstone.block.GlowBlock.getTypeId(GlowBlock.java:195)
	at net.glowstone.block.GlowBlock.getType(GlowBlock.java:190)
	at net.glowstone.block.blocktype.BlockLiquid.calculateTarget(BlockLiquid.java:114)
	at net.glowstone.block.blocktype.BlockLiquid.calculateFlow(BlockLiquid.java:95)
	at net.glowstone.block.blocktype.BlockLiquid.updatePhysics(BlockLiquid.java:201)
	at net.glowstone.block.blocktype.BlockLiquid.receivePulse(BlockLiquid.java:67)
	at net.glowstone.GlowWorld.pulseTickMap(GlowWorld.java:1797)
	at net.glowstone.GlowWorld.pulse(GlowWorld.java:382)
	at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:52)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by mastercoms** [comment]
I have gotten these errors with Glowstone++ generated worlds.

**Comment by Paulomart** [comment]
hmm, first guess, looking at the code would be, that the file pointer is not at the right position when reading

**Comment by mastercoms** [comment]
Duplicate of #199. But I will close that one and move the info over here because this one is more detailed.

**Comment by mastercoms** [comment]
_originally authored by LuxusDarkangel_:

You can see 3 different errors in console regarding terrain/chunk load:
http://pastebin.com/p94Wd35g

**Comment by mastercoms** [comment]
Relevant file: https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/blob/master/src/main/java/net/glowstone/io/anvil/RegionFile.java

**Comment by mastercoms** [comment]
I believe I fixed this. Are you seeing this error anymore?

**Comment by mastercoms** [comment]
Closing this as I haven't been seeing this bug recently when I had been before. (and bug reporter seems to be inactive :frowning:)

**Comment by DX94** [comment]
could you please reopen this, im having kind of the same issue
`java.io.IOException: Invalid length: 2013392284 > 4096
at net.glowstone.io.anvil.RegionFile.getChunkDataInputStream(RegionFile.java:196)
at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:63)
at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:152)
at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:219)
at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:252)
at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:747)
at net.glowstone.GlowWorld.<init>(GlowWorld.java:308)
at net.glowstone.GlowServer.createWorld(GlowServer.java:1510)
at net.glowstone.GlowServer.start(GlowServer.java:509)
at net.glowstone.GlowServer.run(GlowServer.java:442)
at net.glowstone.GlowServer.main(GlowServer.java:299)`

**Comment by gdude2002** [comment]
What version of Glowstone++ are you using?

**Comment by gdude2002** [comment]
There's been no discussion or response on this in four days, so I'm closing again. Please open another ticket if you're prepared to maintain it.

Not that this ticket had anything to do with your issue, though.

**Comment by Xatarch** [comment]
```
[SEVERE] Error while loading chunk (11,-55)
java.io.IOException: Unknown version: 0
    at net.glowstone.io.anvil.RegionFile.getChunkDataInputStream(RegionFile.java:210)
    at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:63)
    at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:147)
    at net.glowstone.GlowChunk.load(GlowChunk.java:188)
    at net.glowstone.generator.populators.StructurePopulator.populate(StructurePopulator.java:36)
    at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:232)
    at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:247)
    at net.glowstone.entity.GlowPlayer.streamBlocks(GlowPlayer.java:695)
    at net.glowstone.entity.GlowPlayer.pulse(GlowPlayer.java:560)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
    at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
    at java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source)
    at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
    at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
    at java.util.stream.ReferencePipeline.forEach(Unknown Source)
    at net.glowstone.GlowWorld.pulsePlayers(GlowWorld.java:483)
    at net.glowstone.GlowWorld.pulse(GlowWorld.java:364)
    at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:139)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

![](https://dl.dropboxusercontent.com/u/1547120/ShareX/2016/July/Discord_2016-07-24_19-30-54.png)

---

_Edited by gdude2002 for formatting and Discord messages_

**Comment by gdude2002** [comment]
This has been confirmed to still be a problem on Discord.

**Comment by mastercoms** [comment]
Better version handling was added in https://github.com/GlowstoneMC/Glowstone/commit/92d688e46cee120abfc45d028677a8b188767700. Perhaps this fixed the issue? I haven't seen this problem for a while.

**Comment by BSFishy** [comment]
I just got this issue again 😝. Here are the errors(There are the two):

    17:02:33 [SEVERE] Error while loading chunk (-7,8)
    java.io.IOException: Invalid length: 136138398 > 4096
            at net.glowstone.io.anvil.RegionFile.getChunkDataInputStream(RegionFile.java:208)
            at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:67)
            at net.glowstone.chunk.ChunkManager.loadChunk(ChunkManager.java:149)
            at net.glowstone.chunk.ChunkManager.populateChunk(ChunkManager.java:216)
            at net.glowstone.chunk.ChunkManager.forcePopulation(ChunkManager.java:249)
            at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:773)
            at net.glowstone.GlowWorld.<init>(GlowWorld.java:319)
            at net.glowstone.GlowServer.createWorld(GlowServer.java:1531)
            at net.glowstone.GlowServer.start(GlowServer.java:515)
            at net.glowstone.GlowServer.run(GlowServer.java:439)
            at net.glowstone.GlowServer.main(GlowServer.java:311)
and:

    17:02:34 [SEVERE] Error while loading chunk (0,-14)
    java.io.IOException: Unknown version: -52
            at net.glowstone.io.anvil.RegionFile.getChunkDataInputStream(RegionFile.java:231)
            at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:67)
            at net.glowstone.chunk.ChunkManager.loadChunk(ChunkManager.java:149)
            at net.glowstone.chunk.ChunkManager.populateChunk(ChunkManager.java:216)
            at net.glowstone.chunk.ChunkManager.forcePopulation(ChunkManager.java:249)
            at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:773)
            at net.glowstone.GlowWorld.<init>(GlowWorld.java:319)
            at net.glowstone.GlowServer.createWorld(GlowServer.java:1531)
            at net.glowstone.GlowServer.start(GlowServer.java:515)
            at net.glowstone.GlowServer.run(GlowServer.java:439)
            at net.glowstone.GlowServer.main(GlowServer.java:311)
Got 5 of these errors (Each different chunks)

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/Glowstone/commit/98aeb192d084e3768b86eb2d2a68020a4b1d9975
