### ISSUE TITLE
Chunk generator problem

### ISSUE THREAD

**Issue by Paulomart** [GlowstoneMC/Glowstone#203]
```
2016/02/15 21:29:45 [SCHWERWIEGEND] Error while populating chunk (15,9)
java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Unknown Source)
    at net.glowstone.generator.populators.overworld.PlainsPopulator.populateOnGround(PlainsPopulator.java:74)
    at net.glowstone.generator.populators.overworld.BiomePopulator.populate(BiomePopulator.java:107)
    at net.glowstone.generator.populators.OverworldPopulator.populate(OverworldPopulator.java:49)
    at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:217)
    at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:231)
    at net.glowstone.entity.GlowPlayer.streamBlocks(GlowPlayer.java:700)
    at net.glowstone.entity.GlowPlayer.pulse(GlowPlayer.java:556)
    at net.glowstone.GlowWorld.pulsePlayers(GlowWorld.java:524)
    at net.glowstone.GlowWorld.pulse(GlowWorld.java:399)
    at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:52)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

```
##

**Comment by jimmikaelkael** [comment]
I guess it means world.getHighestBlockYAt(x, z) have returned 0.

**Comment by Paulomart** [comment]
Was generating fresh chunks, after a long teleport here

**Comment by jimmikaelkael** [comment]
We should have a check before to ROL but I wasn't excepting 0 as highest block... The chunk manager is faulty it seems.

**Comment by gdude2002** [comment]
This ticket needs categorization on the [waffle board](https://waffle.io/GlowstoneMC/Glowstone).

Has this ticket seen any movement or has there been any action expected since the previous comment?

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/Glowstone/commit/1df03e072ec97b26973f53f7749a3ae8d7f8fbcc#diff-e4fce268ee45472d3f6f9d783cb96d5f.
