### ISSUE TITLE
Unknown structure "Iglu" prevents server startup

### ISSUE THREAD

**Issue by Jelmerro** [GlowstoneMC/Glowstone#225]
1 Open an existing world with Igloo's in it
2 Severe error during server startup
3 Server doesn't start and crashes

Log reports the following:

```
2016/03/03 16:22:46 [SEVERE] Error during server startup.
java.lang.IllegalArgumentException: Unknown structure piece type to load: "Iglu"
    at net.glowstone.io.structure.StructurePieceStorage.loadStructurePiece(StructurePieceStorage.java:63)
    at net.glowstone.io.structure.StructureStore.load(StructureStore.java:75)
    at net.glowstone.io.structure.StructureStorage.createStructure(StructureStorage.java:119)
    at net.glowstone.io.structure.StructureStorage.loadStructure(StructureStorage.java:88)
    at net.glowstone.io.nbt.NbtStructureDataService.lambda$readStructuresData$0(NbtStructureDataService.java:53)
    at net.glowstone.io.nbt.NbtStructureDataService$$Lambda$15/317644782.accept(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
    at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
    at java.util.Iterator.forEachRemaining(Unknown Source)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
    at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
    at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
    at java.util.stream.ReferencePipeline.forEach(Unknown Source)
    at net.glowstone.io.nbt.NbtStructureDataService.readStructuresData(NbtStructureDataService.java:52)
    at net.glowstone.GlowWorld.<init>(GlowWorld.java:284)
    at net.glowstone.GlowServer.createWorld(GlowServer.java:1477)
    at net.glowstone.GlowServer.start(GlowServer.java:490)
    at net.glowstone.GlowServer.run(GlowServer.java:433)
    at net.glowstone.GlowServer.main(GlowServer.java:290)
```

EDIT by mastercoms: changed log to multiline code formatting

**Comment by mastercoms** [comment]
Well we don't have any features from 1.9 implemented, but this can be a tracker for two issues: the fact that we crash because of an unknown structure, instead of ignoring it, and a tracker for implementing igloos.

**Comment by jimmikaelkael** [comment]
Creating it should be fairly easy. I can handle that part if no one is already on it...

**Comment by mastercoms** [comment]
I have not started working on it.

**Comment by mastercoms** [comment]
@Jelmerro Could you provide a world with an igloo for testing?

**Comment by Jelmerro** [comment]
Our world has a few pretty close to spawn, seed for that is 954601601153891725 :)

**Comment by aramperes** [comment]
@Jelmerro Could you give us the coordinates of one of the igloos? Thanks =)

**Comment by Jelmerro** [comment]
You can use AmidstExporter, the 1.9 fork of Amidst, to find some but the nearest one seems to be at -360 184

**Comment by mastercoms** [comment]
Glowstone++ successfully ignores unknown structures! (fixed in https://github.com/GlowstoneMC/GlowstonePlusPlus/commit/2e1edc2b2a5ecfcbe439dec93d0ef2fca5210953)
