### ISSUE TITLE
Unknown biome id from vanilla generated world

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone#239]
```
[SEVERE] Error while generating chunk (15,-14)
java.lang.ArrayIndexOutOfBoundsException: 1002
        at net.glowstone.constants.GlowBiome.getBiome(GlowBiome.java:106)
        at net.glowstone.generator.OverworldGenerator.generateTerrainDensity(OverworldGenerator.java:269)
        at net.glowstone.generator.OverworldGenerator.generateRawTerrain(OverworldGenerator.java:172)
        at net.glowstone.generator.OverworldGenerator.generateChunkData(OverworldGenerator.java:121)
        at net.glowstone.ChunkManager.generateChunk(ChunkManager.java:265)
        at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:163)
        at net.glowstone.GlowChunk.load(GlowChunk.java:187)
        at net.glowstone.generator.populators.StructurePopulator.populate(StructurePopulator.java:36)
        at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:230)
        at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:245)
        at net.glowstone.entity.GlowPlayer.streamBlocks(GlowPlayer.java:685)
        at net.glowstone.entity.GlowPlayer.pulse(GlowPlayer.java:550)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at net.glowstone.GlowWorld.pulsePlayers(GlowWorld.java:492)
        at net.glowstone.GlowWorld.pulse(GlowWorld.java:373)
        at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:139)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

This error was thrown when I was entering a vanilla generated world. I eventually spawned in an ocean near a mushroom island.

**Comment by mastercoms** [comment]
Kind of fixed in https://github.com/GlowstoneMC/GlowstonePlusPlus/commit/f7bbaae285ee6ae8483337df82b0f2dc2b1f2f4a, but we need to figure out what that biome id is.

**Comment by ghost** [comment]
This also happens sometimes when generating a new world with Glowstone itself (non-vanilla world). When using `7944974524167113781` as seed for example, the following stack trace is produced for certain chunks, when explicitly logging the stack trace:

```
Unknown biome id: 1,001!
java.lang.Exception: Stack trace
    at java.lang.Thread.dumpStack(Thread.java:1329)
    at net.glowstone.constants.GlowBiome.getBiome(GlowBiome.java:112)
    at net.glowstone.generator.OverworldGenerator.generateTerrainDensity(OverworldGenerator.java:275)
    at net.glowstone.generator.OverworldGenerator.generateRawTerrain(OverworldGenerator.java:172)
    at net.glowstone.generator.OverworldGenerator.generateChunkData(OverworldGenerator.java:121)
    at net.glowstone.ChunkManager.generateChunk(ChunkManager.java:274)
    at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:171)
    at net.glowstone.GlowChunk.load(GlowChunk.java:187)
    at net.glowstone.generator.populators.StructurePopulator.populate(StructurePopulator.java:36)
    at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:238)
    at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:253)
    at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:748)
    at net.glowstone.GlowWorld.setSpawnLocation(GlowWorld.java:708)
    at net.glowstone.GlowWorld.<init>(GlowWorld.java:307)
    at net.glowstone.GlowServer.createWorld(GlowServer.java:1499)
    at net.glowstone.GlowServer.start(GlowServer.java:505)
    at net.glowstone.GlowServer.run(GlowServer.java:441)
    at net.glowstone.GlowServer.main(GlowServer.java:298)
```

Instead of `OverworldGenerator.generateTerrainDensity(OverworldGenerator.java:275)`, `OverworldGenerator.generateTerrainDensity(OverworldGenerator.java:269)` may also be encountered.

@jimmikaelkael, perhaps you know a way to fix this?

**Comment by jimmikaelkael** [comment]
Yeah BiomeMapLayer has been broken when migrating to 1.9, and sadly there's several classes from the biomegrid generator that has been badly altered.

Broken code from biomegrid:
- BiomeMapLayer.java
- BiomeThinEdgeMapLayer.java
- BiomeVariationMapLayer.java
- RarePlainsMapLayer.java

And more... Seriously it's a total mess.

Culprit:
https://github.com/GlowstoneMC/GlowstonePlusPlus/commit/84572b0138320fdeb4e678bae6a1366005ca934d#diff-2d6fccaee33ada3923696a7c4ec4b411

I'm wondering how it can actually have a correct world generation...

I'm filing a PR to fix this.

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/GlowstonePlusPlus/commit/a58ba1f6583c19ddfd3157d4b610a15c654b2d00
