### ISSUE TITLE
Chunk invalid length

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#256]
An odd crash occurs at random times with chunk loading when BlockWater does it's physics. Might be related to the Anvil Chunk loader.

I am not exactly sure _when_ this happens, but it seems to occur when the server has been loaded for ~15 minutes and a player joins and moves around.

Stacktrace:

```
[SEVERE] Error while loading chunk (35,4)
java.io.IOException: Invalid length: 2013392221 > 4096
    at net.glowstone.io.anvil.RegionFile.getChunkDataInputStream(RegionFile.java:196)
    at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:63)
    at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:145)
    at net.glowstone.GlowChunk.load(GlowChunk.java:187)
    at net.glowstone.GlowChunk.load(GlowChunk.java:180)
    at net.glowstone.GlowChunk.getSection(GlowChunk.java:281)
    at net.glowstone.GlowChunk.getType(GlowChunk.java:321)
    at net.glowstone.block.GlowBlock.getTypeIdNoCache(GlowBlock.java:201)
    at net.glowstone.block.GlowBlock.getType(GlowBlock.java:182)
    at net.glowstone.block.blocktype.BlockWater.hasNearSolidBlock(BlockWater.java:46)
    at net.glowstone.block.blocktype.BlockWater.updateBlock(BlockWater.java:30)
    at net.glowstone.GlowWorld.updateBlocksInSection(GlowWorld.java:436)
    at net.glowstone.GlowWorld.updateBlocksInActiveChunks(GlowWorld.java:418)
    at net.glowstone.GlowWorld.pulse(GlowWorld.java:370)
    at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:139)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by mastercoms** [comment]
Water is probably trying to modify a block in a chunk that hasn't been loaded.

**Comment by aramperes** [comment]
I find it odd that it does it without me/the server doing anything. In fact, it does it at completely random times, when the server and the player are idle. I wouldn't think it would update blocks when literally nothing is happening.

**Comment by GreenBeard** [comment]
This might be fixed in #285 . I'm not really sure but it does stop lots of cases of background ticking of water.

**Comment by aramperes** [comment]
I am considering closing this; I haven't encountered this for a while. Seems to have been fixed by #293 ([this line](https://github.com/GlowstoneMC/Glowstone/pull/293/files#diff-70c1e490963d7fe75aa5d2e185842bf2R152))

**Comment by aramperes** [comment]
Has this been occurring to someone since the latest commits? Please let me know here.

**Comment by BSFishy** [comment]
@momothereal I just got this with the latest build of Glowstone. I don't even think I have any anvils... (not sure if that has anything to do with the actual error, but just thought I'd put that out there 😛 )

**Comment by Paulomart** [comment]
@LousyLynx anvil is the format the save is in.

**Comment by BSFishy** [comment]
Oh 😛

**Comment by aramperes** [comment]
@LousyLynx Do you have a stacktrace for your error?
Perhaps the exception is caused by another block than liquid.

**Comment by mastercoms** [comment]
Shouldn't occur anymore, but provide logs if you encounter it.
