### ISSUE TITLE
Crash on my server

### ISSUE THREAD

**Issue by Sephyroth234** [GlowstoneMC/Glowstone#262]
```
18:21:44 [INFOS] This server is running Glowstone++ version 1.9-SNAPSHOT-"d087be6" (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
18:21:44 [INFOS] Creating default config: config\glowstone.yml
18:21:44 [INFOS] Recipes: 295 shaped, 63 shapeless, 26 furnace, 10 dynamic, 28 fuels.
18:21:44 [INFOS] Downloading sqlite-jdbc 3.7.2...
18:21:44 [INFOS] Downloading slf4j-jdk14 1.7.15...
18:21:44 [INFOS] Downloading mysql-connector-java 5.1.38...
18:21:45 [INFOS] Downloaded slf4j-jdk14 1.7.15.
18:21:49 [INFOS] Scanning plugins...
18:21:49 [INFOS] Created default config: config\help.yml
18:21:50 [INFOS] Preparing spawn for world...
18:21:51 [INFOS] Preparing spawn for world: 0%
18:21:52 [INFOS] Preparing spawn for world: 3%
18:21:53 [INFOS] Preparing spawn for world: 12%
18:21:54 [INFOS] dungeon generated: -123,3,291
18:21:54 [INFOS] Preparing spawn for world: 28%
18:21:55 [INFOS] Preparing spawn for world: 46%
18:21:56 [INFOS] Preparing spawn for world: 62%
18:21:57 [INFOS] Downloaded mysql-connector-java 5.1.38.
18:21:57 [INFOS] Preparing spawn for world: 88%
18:21:58 [INFOS] Preparing spawn for world: done
18:21:58 [INFOS] Preparing spawn for world_nether...
18:21:59 [INFOS] Preparing spawn for world_nether: 48%
18:22:00 [INFOS] Preparing spawn for world_nether: done
18:22:00 [INFOS] Preparing spawn for world_the_end...
18:22:00 [INFOS] Preparing spawn for world_the_end: done
18:22:00 [INFOS] Created default config: config\commands.yml
18:22:00 [INFOS] Created default config: config\permissions.yml
18:22:00 [INFOS] Binding to address: 0.0.0.0/0.0.0.0:25565...
18:22:00 [INFOS] Successfully bound to: /0:0:0:0:0:0:0:0:25565
18:22:00 [INFOS] Ready for connections.
18:22:12 [INFOS] Downloaded sqlite-jdbc 3.7.2.
18:32:00 [GRAVE] Error while loading chunk (-14,22)
java.io.IOException: Invalid length: 1459204021 > 4096
        at net.glowstone.io.anvil.RegionFile.getChunkDataInputStream(RegionFile.java:196)
        at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:63)
        at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:152)
        at net.glowstone.GlowChunk.load(GlowChunk.java:187)
        at net.glowstone.GlowChunk.load(GlowChunk.java:180)
        at net.glowstone.GlowChunk.getSection(GlowChunk.java:281)
        at net.glowstone.GlowChunk.getType(GlowChunk.java:321)
        at net.glowstone.block.GlowBlock.getTypeIdNoCache(GlowBlock.java:201)
        at net.glowstone.block.GlowBlock.getType(GlowBlock.java:182)
        at net.glowstone.block.blocktype.BlockLiquid.calculateTarget(BlockLiquid.java:152)
        at net.glowstone.block.blocktype.BlockLiquid.calculateFlow(BlockLiquid.java:133)
        at net.glowstone.block.blocktype.BlockLiquid.updatePhysics(BlockLiquid.java:247)
        at net.glowstone.block.blocktype.BlockLiquid.receivePulse(BlockLiquid.java:113)
        at net.glowstone.GlowWorld.lambda$pulseTickMap$20(GlowWorld.java:1784)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap$EntrySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at net.glowstone.GlowWorld.pulseTickMap(GlowWorld.java:1780)
        at net.glowstone.GlowWorld.pulse(GlowWorld.java:356)
        at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:139)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
18:37:45 [INFOS] Sephyroth234 [/127.0.0.1:56541] connected, UUID: 7d4b1f6e-2fab-4d4c-95e8-930b10e3c94f
18:37:45 [INFOS] Sephyroth234 joined the game
18:38:00 [INFOS] Sephyroth234 issued command: /time set day
>op Sephyroth234
18:38:14 [INFOS] CONSOLE: Opped Sephyroth234
18:39:33 [INFOS] Sephyroth234 issued command: /time set day
18:39:33 [INFOS] Sephyroth234: Set time to 0
18:39:51 [INFOS] Sephyroth234 issued command: /gm 1
18:39:54 [INFOS] Sephyroth234 issued command: /gamemode 1
18:39:54 [INFOS] Sephyroth234: Set own game mode to CREATIVE mode
18:39:57 [INFOS] Sephyroth234 issued command: /help
18:40:01 [INFOS] Sephyroth234 issued command: /pl
18:41:42 [INFOS] Sephyroth234 has just earned the achievement [Taking Inventory]
18:46:40 [INFOS] Sephyroth234 issued command: /help
18:46:46 [INFOS] Sephyroth234 issued command: /help Bukkit
18:47:01 [GRAVE] Error while loading chunk (-12,28)
java.io.IOException: Invalid length: 1459204921 > 4096
        at net.glowstone.io.anvil.RegionFile.getChunkDataInputStream(RegionFile.java:196)
        at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:63)
        at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:152)
        at net.glowstone.GlowChunk.load(GlowChunk.java:187)
        at net.glowstone.GlowChunk.load(GlowChunk.java:180)
        at net.glowstone.GlowChunk.getSection(GlowChunk.java:281)
        at net.glowstone.GlowChunk.getType(GlowChunk.java:321)
        at net.glowstone.block.GlowBlock.getTypeIdNoCache(GlowBlock.java:201)
        at net.glowstone.block.GlowBlock.getType(GlowBlock.java:182)
        at net.glowstone.block.blocktype.BlockLiquid.calculateTarget(BlockLiquid.java:152)
        at net.glowstone.block.blocktype.BlockLiquid.calculateFlow(BlockLiquid.java:133)
        at net.glowstone.block.blocktype.BlockLiquid.updatePhysics(BlockLiquid.java:247)
        at net.glowstone.block.blocktype.BlockLiquid.receivePulse(BlockLiquid.java:113)
        at net.glowstone.GlowWorld.lambda$pulseTickMap$20(GlowWorld.java:1784)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap$EntrySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at net.glowstone.GlowWorld.pulseTickMap(GlowWorld.java:1780)
        at net.glowstone.GlowWorld.pulse(GlowWorld.java:356)
        at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:139)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by aramperes** [comment]
Probably caused by the same bug as #256.

**Comment by mastercoms** [comment]
I'm considering this a dupe of #256.
