### ISSUE TITLE
Player Teleport to Custom World Causes Strange Behaviour and Console Errors

### ISSUE THREAD

**Issue by alptraumhavok** [GlowstoneMC/Glowstone#270]
I'm currently developing a Bukkit plugin but have encountered some strange issues when attempting to teleport any player to a lobby map at login.  The teleport works every other login but there are always a constant stream of PlayerLookMessage errors related to the GlowWorld not matching.

**The relevant code:**

``` java
public void onEnable() {
    saveDefaultConfig();
    FileConfiguration config = this.getConfig();
        String lobbyName = config.getString("lobby_world");
    if(!lobbyName.isEmpty())
    {   
        getServer().createWorld(new WorldCreator(lobbyName));
        getServer().getPluginManager().registerEvents(new PlayerEventHandler(), this);
    } else {
        // Handle errors
    }       
}

public void onLogin(PlayerLoginEvent event) {
    Player player = event.getPlayer();
    World world = Bukkit.getWorld("lobby");
    Console.sendMessage("Teleporting player to "+world.getName());
    Location loc = new Location(world, 0.0, 5.0, 0.0);
    player.teleport(loc);
}
```

**The Errors:**

```
java.lang.IllegalArgumentException: Cannot setRawLocation to a different world (got GlowWorld(name=lobby), expected GlowWorld(name=world))
        at net.glowstone.entity.GlowEntity.setRawLocation(GlowEntity.java:429)
        at net.glowstone.entity.GlowEntity.setRawLocation(GlowEntity.java:483)
        at net.glowstone.net.handler.play.player.PlayerUpdateHandler.handle(PlayerUpdateHandler.java:89)
        at net.glowstone.net.handler.play.player.PlayerUpdateHandler.handle(PlayerUpdateHandler.java:16)
        at net.glowstone.libs.com.flowpowered.network.session.BasicSession.handleMessage(BasicSession.java:80)
        at net.glowstone.libs.com.flowpowered.network.session.BasicSession.messageReceived(BasicSession.java:139)
        at net.glowstone.net.GlowSession.pulse(GlowSession.java:462)
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649)
        at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:144)
        at net.glowstone.scheduler.GlowScheduler.lambda$start$0(GlowScheduler.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
18:13:23 [SEVERE] Error while handling PlayerLookMessage(yaw=299.25006, pitch=18.150005, onGround=true) (handler: PlayerUpdateHandler)
java.lang.IllegalArgumentException: Cannot setRawLocation to a different world (got GlowWorld(name=lobby), expected GlowWorld(name=world))
        at net.glowstone.entity.GlowEntity.setRawLocation(GlowEntity.java:429)
        at net.glowstone.entity.GlowEntity.setRawLocation(GlowEntity.java:483)
        at net.glowstone.net.handler.play.player.PlayerUpdateHandler.handle(PlayerUpdateHandler.java:89)
        at net.glowstone.net.handler.play.player.PlayerUpdateHandler.handle(PlayerUpdateHandler.java:16)
        at net.glowstone.libs.com.flowpowered.network.session.BasicSession.handleMessage(BasicSession.java:80)
        at net.glowstone.libs.com.flowpowered.network.session.BasicSession.messageReceived(BasicSession.java:139)
        at net.glowstone.net.GlowSession.pulse(GlowSession.java:462)
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649)
        at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:144)
        at net.glowstone.scheduler.GlowScheduler.lambda$start$0(GlowScheduler.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
18:13:23 [SEVERE] Error while handling PlayerLookMessage(yaw=338.55005, pitch=23.400005, onGround=true) (handler: PlayerUpdateHandler)
java.lang.IllegalArgumentException: Cannot setRawLocation to a different world (got GlowWorld(name=lobby), expected GlowWorld(name=world))
        at net.glowstone.entity.GlowEntity.setRawLocation(GlowEntity.java:429)
        at net.glowstone.entity.GlowEntity.setRawLocation(GlowEntity.java:483)
        at net.glowstone.net.handler.play.player.PlayerUpdateHandler.handle(PlayerUpdateHandler.java:89)
        at net.glowstone.net.handler.play.player.PlayerUpdateHandler.handle(PlayerUpdateHandler.java:16)
        at net.glowstone.libs.com.flowpowered.network.session.BasicSession.handleMessage(BasicSession.java:80)
        at net.glowstone.libs.com.flowpowered.network.session.BasicSession.messageReceived(BasicSession.java:139)
        at net.glowstone.net.GlowSession.pulse(GlowSession.java:462)
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649)
        at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:144)
        at net.glowstone.scheduler.GlowScheduler.lambda$start$0(GlowScheduler.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
18:13:23 [SEVERE] Error while handling PlayerLookMessage(yaw=12.300049, pitch=19.650005, onGround=true) (handler: PlayerUpdateHandler)
java.lang.IllegalArgumentException: Cannot setRawLocation to a different world (got GlowWorld(name=lobby), expected GlowWorld(name=world))
        at net.glowstone.entity.GlowEntity.setRawLocation(GlowEntity.java:429)
        at net.glowstone.entity.GlowEntity.setRawLocation(GlowEntity.java:483)
        at net.glowstone.net.handler.play.player.PlayerUpdateHandler.handle(PlayerUpdateHandler.java:89)
        at net.glowstone.net.handler.play.player.PlayerUpdateHandler.handle(PlayerUpdateHandler.java:16)
        at net.glowstone.libs.com.flowpowered.network.session.BasicSession.handleMessage(BasicSession.java:80)
        at net.glowstone.libs.com.flowpowered.network.session.BasicSession.messageReceived(BasicSession.java:139)
        at net.glowstone.net.GlowSession.pulse(GlowSession.java:462)
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649)
        at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:144)
        at net.glowstone.scheduler.GlowScheduler.lambda$start$0(GlowScheduler.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
18:13:23 [SEVERE] Error while handling PlayerLookMessage(yaw=28.950043, pitch=17.400005, onGround=true) (handler: PlayerUpdateHandler)
java.lang.IllegalArgumentException: Cannot setRawLocation to a different world (got GlowWorld(name=lobby), expected GlowWorld(name=world))
        at net.glowstone.entity.GlowEntity.setRawLocation(GlowEntity.java:429)
        at net.glowstone.entity.GlowEntity.setRawLocation(GlowEntity.java:483)
        at net.glowstone.net.handler.play.player.PlayerUpdateHandler.handle(PlayerUpdateHandler.java:89)
        at net.glowstone.net.handler.play.player.PlayerUpdateHandler.handle(PlayerUpdateHandler.java:16)
        at net.glowstone.libs.com.flowpowered.network.session.BasicSession.handleMessage(BasicSession.java:80)
        at net.glowstone.libs.com.flowpowered.network.session.BasicSession.messageReceived(BasicSession.java:139)
        at net.glowstone.net.GlowSession.pulse(GlowSession.java:462)
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649)
        at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:144)
        at net.glowstone.scheduler.GlowScheduler.lambda$start$0(GlowScheduler.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by alptraumhavok** [comment]
This call fixes the problem but I'm at a loss as to why we need to pass the world object to the Location constructor and then once again explicitly using Location::setWorld(World);

**This Code Works**

```
public void onLogin(PlayerLoginEvent event) {
    Player player = event.getPlayer();
    FileConfiguration config = mPlugin.getConfig();
    World world = Bukkit.getWorld(config.getString("lobby_world"));
    Location loc = new Location(world, 0.0, 0.0, 0.0);
    // This line of code solved the issue
        loc.setWorld(world);
    player.teleport(loc);
}
```

**The Call:**

``` java
loc.setWorld(world);
```

**Comment by gdude2002** [comment]
Can you paste a larger snippet? How exactly are you moving the player?

(By the way, you need three backticks (```) for a code block)

EDIT: I'm stupid, just saw your code in the ticket. Give me a sec.

**Comment by gdude2002** [comment]
For maintainers: Looks like we need a call to `location.setWorld(world)` on [the line before this one](https://github.com/GlowstoneMC/GlowstonePlusPlus/blob/f84d3f08644f2fd43d2828468855bedd87ac9060/src/main/java/net/glowstone/entity/GlowEntity.java#L304).

I don't have the time or software to test that at the moment, unfortunately.
@alptraumhavok Would you mind quickly writing up a PR and testing it?

**Comment by alptraumhavok** [comment]
@gdude2002 Sure thing, I don't mind one bit.

**Comment by Paulomart** [comment]
I think it's wrong to TP on login anyways. You should use PlayerSpawnLocationEvent.

**Comment by gdude2002** [comment]
Perhaps, but this does showcase an underlying bug

**Comment by Paulomart** [comment]
Ah okay then

**Comment by alptraumhavok** [comment]
Sorry been out of town with the whole Mother's Day adventure.

@Paulomart, Thank you for the info.  I agree the PlayerSpawnEvent is a better place to perform the teleport but the existing issue would still remain due to the use of teleport.

@gdude2002, I will be making the Pull Request today but I wanted to look into fixing the issue in the Location object if possible and straightforward otherwise I'll just add the setWorld call to the player object as you suggested.

**Comment by gdude2002** [comment]
It's not an issue with the Location object (as far as I can see), that's behaving as expected (and in accordance with the Bukkit API). It should work with just that one line change.

**Comment by gdude2002** [comment]
@alptraumhavok Did you end up making that PR?

**Comment by gdude2002** [comment]
This ticket needs categorization on the [waffle board](https://waffle.io/GlowstoneMC/Glowstone).

Has this ticket seen any movement or has there been any action expected since the previous comment?

**Comment by alptraumhavok** [comment]
Sorry I forgot to update this issue.  I ended up setting up a clean
environment using an aws server and I was unable to recreate the issue
using a fresh pull from the repo.

On Wed, Jun 22, 2016 at 6:18 AM, Gareth Coles notifications@github.com
wrote:

> This ticket needs categorization on the waffle board
> https://waffle.io/GlowstoneMC/Glowstone.
> 
> Has this ticket seen any movement or has there been any action expected
> since the previous comment?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/GlowstoneMC/Glowstone/issues/270#issuecomment-227714337,
> or mute the thread
> https://github.com/notifications/unsubscribe/ALZNN3rmJiOeuvAf-kO0SwtOlpuzkTwRks5qORoEgaJpZM4IZGQu
> .

## 

V/R,

Kerry L. Rodgers
https://www.linkedin.com/in/kerryrodgers

```
                                             \¦/
                                           (ò ó)
```

______________________o0o__ (_)___o0o__
**_¦__**_¦_____¦_____¦_____¦_____¦_____¦_
¦_____¦_____¦_____¦_____¦_____¦_____¦_____¦
**_¦__**_¦_____¦_____¦_____¦_____¦_____¦__
¦_____¦_____¦_____¦_____¦_____¦_____¦_____¦

**Comment by gdude2002** [comment]
That's cool, maybe someone else fixed it and forgot to update the ticket.

In that case, I'm going to close this - Feel free to comment or open another ticket if you find it's still an issue!
