### ISSUE TITLE
Is ProtocolLib v3.6.5 not compatible with Glowstone 1.8.9?

### ISSUE THREAD

**Issue by Small-Ku** [GlowstoneMC/Glowstone#274]
It said that "Error loading ProtocolLib v3.6.5"is a serious error...

```
2016/05/21 13:01:33 [資訊] Downloading sqlite-jdbc 3.7.2...
2016/05/21 13:01:33 [資訊] Downloading slf4j-jdk14 1.7.15...
2016/05/21 13:01:33 [資訊] Downloading mysql-connector-java 5.1.38...
2016/05/21 13:01:34 [警告] Failed to download: slf4j-jdk14 1.7.15
java.io.IOException: Server returned HTTP response code: 403 for URL: http://repo.glowstone.net/service/local/repositories/central/content/org/slf4j/slf4j-jdk14/1.7.15/slf4j-jdk14-1.7.15.jar
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at java.net.URL.openStream(Unknown Source)
    at net.glowstone.util.LibraryManager$LibraryDownloader.run(LibraryManager.java:79)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2016/05/21 13:01:34 [警告] Failed to download: mysql-connector-java 5.1.38
java.io.IOException: Server returned HTTP response code: 403 for URL: http://repo.glowstone.net/service/local/repositories/central/content/mysql/mysql-connector-java/5.1.38/mysql-connector-java-5.1.38.jar
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at java.net.URL.openStream(Unknown Source)
    at net.glowstone.util.LibraryManager$LibraryDownloader.run(LibraryManager.java:79)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2016/05/21 13:01:34 [警告] Failed to download: sqlite-jdbc 3.7.2
java.io.IOException: Server returned HTTP response code: 403 for URL: http://repo.glowstone.net/service/local/repositories/central/content/org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.jar
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at java.net.URL.openStream(Unknown Source)
    at net.glowstone.util.LibraryManager$LibraryDownloader.run(LibraryManager.java:79)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2016/05/21 13:01:34 [資訊] Scanning plugins...
2016/05/21 13:01:34 [資訊] PluginTypeDetector: found 1 Bukkit, 0 Sponge, 0 Forge, 0 Canary, 0 unknown plugins (total 1)
2016/05/21 13:01:34 [資訊] Set PluginClassLoader as parallel capable
2016/05/21 13:01:34 [警告] [ProtocolLib] [ProtocolLibrary] Unable to retrieve current Minecraft version. Assuming (MC: 1.8.8)
java.lang.NullPointerException
    at java.util.regex.Matcher.getTextLength(Unknown Source)
    at java.util.regex.Matcher.reset(Unknown Source)
    at java.util.regex.Matcher.<init>(Unknown Source)
    at java.util.regex.Pattern.matcher(Unknown Source)
    at com.comphenix.protocol.utility.MinecraftVersion.extractVersion(MinecraftVersion.java:303)
    at com.comphenix.protocol.utility.MinecraftVersion.<init>(MinecraftVersion.java:92)
    at com.comphenix.protocol.ProtocolLibrary.verifyMinecraftVersion(ProtocolLibrary.java:471)
    at com.comphenix.protocol.ProtocolLibrary.onLoad(ProtocolLibrary.java:216)
    at net.glowstone.GlowServer.loadPlugins(GlowServer.java:723)
    at net.glowstone.GlowServer.start(GlowServer.java:462)
    at net.glowstone.GlowServer.run(GlowServer.java:429)
    at net.glowstone.GlowServer.main(GlowServer.java:286)
2016/05/21 13:01:34 [嚴重] Error loading ProtocolLib v3.6.5
java.lang.NullPointerException
    at com.comphenix.protocol.error.DetailedErrorReporter.addPrefix(DetailedErrorReporter.java:450)
    at com.comphenix.protocol.error.DetailedErrorReporter.reportDetailed(DetailedErrorReporter.java:390)
    at com.comphenix.protocol.error.DelegatedErrorReporter.reportDetailed(DelegatedErrorReporter.java:63)
    at com.comphenix.protocol.error.DelegatedErrorReporter.reportDetailed(DelegatedErrorReporter.java:87)
    at com.comphenix.protocol.ProtocolLibrary.onLoad(ProtocolLibrary.java:256)
    at net.glowstone.GlowServer.loadPlugins(GlowServer.java:723)
    at net.glowstone.GlowServer.start(GlowServer.java:462)
    at net.glowstone.GlowServer.run(GlowServer.java:429)
    at net.glowstone.GlowServer.main(GlowServer.java:286)
2016/05/21 13:01:34 [資訊] [ProtocolLib] Enabling ProtocolLib v3.6.5
2016/05/21 13:01:34 [警告] [ProtocolLib] [MinecraftReflection] Unable to load MCPC/Cauldron remapper.
2016/05/21 13:01:34 [嚴重] Error occurred while enabling ProtocolLib v3.6.5 (Is it up to date?)
java.lang.NullPointerException
    at com.comphenix.protocol.error.DetailedErrorReporter.addPrefix(DetailedErrorReporter.java:450)
    at com.comphenix.protocol.error.DetailedErrorReporter.reportDetailed(DetailedErrorReporter.java:390)
    at com.comphenix.protocol.error.DelegatedErrorReporter.reportDetailed(DelegatedErrorReporter.java:63)
    at com.comphenix.protocol.error.DelegatedErrorReporter.reportDetailed(DelegatedErrorReporter.java:87)
    at com.comphenix.protocol.ProtocolLibrary.onEnable(ProtocolLibrary.java:425)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:321)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:423)
    at net.glowstone.GlowServer.enablePlugins(GlowServer.java:798)
    at net.glowstone.GlowServer.start(GlowServer.java:463)
    at net.glowstone.GlowServer.run(GlowServer.java:429)
    at net.glowstone.GlowServer.main(GlowServer.java:286)
2016/05/21 13:01:34 [資訊] [ProtocolLib] Disabling ProtocolLib v3.6.5
2016/05/21 13:01:34 [資訊] Preparing spawn for world...
2016/05/21 13:01:35 [資訊] Preparing spawn for world: done
2016/05/21 13:01:35 [資訊] Preparing spawn for world_nether...
2016/05/21 13:01:36 [資訊] Preparing spawn for world_nether: done
2016/05/21 13:01:36 [資訊] Preparing spawn for world_the_end...
2016/05/21 13:01:36 [資訊] Preparing spawn for world_the_end: done
2016/05/21 13:01:36 [資訊] Binding to address: 0.0.0.0/0.0.0.0:25565...
2016/05/21 13:01:37 [資訊] Successfully bound to: /0:0:0:0:0:0:0:0:25565
2016/05/21 13:01:37 [資訊] Ready for connections.
2016/05/21 13:01:43 [資訊] Small_Ku [/127.0.0.1:6999] connected, UUID: 0190680a-dc4d-4b8c-b92e-539a0ffdf8ac
2016/05/21 13:01:43 [資訊] §eSmall_Ku joined the game
2016/05/21 13:01:43 [資訊] Small_Ku[/127.0.0.1:6999] registered channel: FML|HS
2016/05/21 13:01:43 [資訊] Small_Ku[/127.0.0.1:6999] registered channel: FML
2016/05/21 13:01:43 [資訊] Small_Ku[/127.0.0.1:6999] registered channel: FML|MP
2016/05/21 13:01:43 [資訊] Small_Ku[/127.0.0.1:6999] registered channel: WECUI
2016/05/21 13:01:43 [資訊] Small_Ku[/127.0.0.1:6999] registered channel: FML
2016/05/21 13:01:43 [資訊] Small_Ku[/127.0.0.1:6999] registered channel: FORGE
2016/05/21 13:01:43 [資訊] Small_Ku[/127.0.0.1:6999] registered channel: InventoryTweaks
2016/05/21 13:01:43 [資訊] Client brand of Small_Ku is: fml,forge
2016/05/21 13:01:43 [資訊] Small_Ku[/127.0.0.1:6999] registered channel: WECUI
2016/05/21 13:01:43 [資訊] Small_Ku[/127.0.0.1:6999] registered channel: PERMISSIONSREPL
2016/05/21 13:01:43 [資訊] Small_Ku[/127.0.0.1:6999] registered channel: DaFlight
2016/05/21 13:02:56 [資訊] Small_Ku issued command: /pl
2016/05/21 13:02:59 [資訊] Small_Ku has just earned the achievement §a[Taking Inventory]
2016/05/21 13:04:53 [資訊] CONSOLE: Stopping the server..
2016/05/21 13:04:53 [資訊] The server is shutting down...
2016/05/21 13:04:53 [資訊] Small_Ku kicked: Server shutting down.
2016/05/21 13:04:53 [資訊] Saving world: world
2016/05/21 13:04:55 [資訊] Saving world: world_nether
2016/05/21 13:04:56 [資訊] Saving world: world_the_end
```

**Comment by Paulomart** [comment]
No ProtocolLib is for spigot only.

**Comment by gdude2002** [comment]
Yup, it doesn't work with Glowstone, especially given that Glowstone doesn't support NMS plugins.
