### ISSUE TITLE
Attempt to delete all items in inventory (Destroy items button) throws Exception

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#276]
```
Error while handling CreativeItemMessage(slot=45, item=null) (handler: CreativeItemHandler)
java.lang.IllegalArgumentException: Slot out of range [0,45): 45
        at net.glowstone.inventory.GlowInventoryView.checkSlot(GlowInventoryView.java:86)
        at net.glowstone.inventory.GlowInventoryView.getItem(GlowInventoryView.java:71)
        at net.glowstone.net.handler.play.inv.CreativeItemHandler.handle(CreativeItemHandler.java:58)
        at net.glowstone.net.handler.play.inv.CreativeItemHandler.handle(CreativeItemHandler.java:20)
        at net.glowstone.libs.com.flowpowered.network.session.BasicSession.handleMessage(BasicSession.java:80)
        at net.glowstone.libs.com.flowpowered.network.session.BasicSession.messageReceived(BasicSession.java:139)
        at net.glowstone.net.GlowSession.pulse(GlowSession.java:462)
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(Unknown Source)
        at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:144)
        at net.glowstone.scheduler.GlowScheduler.lambda$start$0(GlowScheduler.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

![To see what I mean](https://cloud.githubusercontent.com/assets/17110757/15655288/0e2baa76-269c-11e6-8723-6ef043712266.gif)

**Comment by Shad0wCore** [comment]
#278

**Comment by Shad0wCore** [comment]
#277

**Comment by Shad0wCore** [comment]
Ignoring inventory destroy item slot #278

**Comment by gdude2002** [comment]
This shouldn't be closed until a verified fix or solution has been found.
