### ISSUE TITLE
GlowInventory.setContents() throws error

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#296]
I don't know what happened. They only thing what I have got is this:

```
java.lang.NullPointerException
        at net.glowstone.inventory.GlowInventory.setContents(GlowInventory.java:475)
        at net.impulse.server.menus.SaveOptionMenu.initialization(SaveOptionMenu.java:43)
        at net.impulse.client.gui.AbstractImpulseMenu.<init>(AbstractImpulseMenu.java:23)
        at net.impulse.server.menus.SaveOptionMenu.<init>(SaveOptionMenu.java:25)
        at net.impulse.ImpulseKernel.onEnable(ImpulseKernel.java:36)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:304)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:428)
        at net.glowstone.GlowServer.enablePlugins(GlowServer.java:831)
        at net.glowstone.GlowServer.start(GlowServer.java:529)
        at net.glowstone.GlowServer.run(GlowServer.java:454)
        at net.glowstone.GlowServer.main(GlowServer.java:311)
```

**Comment by ghost** [comment]
I'm sorry, it was a mistake by me :sweat_smile:
