### ISSUE TITLE
Skins and Skulls are not working and throwing exceptions. (NBT)

### ISSUE THREAD

**Issue by FastFelix771** [GlowstoneMC/Glowstone#344]
On my imported Spigot World, i can't see my real skin (only the default Steve) and ALL skulls that are placed in the world turns into a usual player head and throws the following error:

```
[SEVERE] Error loading tile entity at GlowBlock{chunk=GlowChunk{world=spigotworld,x=85,z=106},x=1361,y=137,z=1710,type=SKULL,data=1}: Skull
java.lang.IllegalArgumentException: Compound does not contain StringTag "Name"
    at net.glowstone.util.nbt.CompoundTag.getTag(CompoundTag.java:272)
    at net.glowstone.util.nbt.CompoundTag.get(CompoundTag.java:266)
    at net.glowstone.util.nbt.CompoundTag.getString(CompoundTag.java:103)
    at net.glowstone.entity.meta.profile.PlayerProfile.fromNBT(PlayerProfile.java:90)
    at net.glowstone.block.entity.TESkull.loadNbt(TESkull.java:35)
    at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:130)
    at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:147)
    at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:214)
    at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:247)
    at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:738)
    at net.glowstone.GlowWorld.<init>(GlowWorld.java:299)
    at net.glowstone.GlowServer.createWorld(GlowServer.java:1520)
    at net.glowstone.GlowServer.start(GlowServer.java:505)
    at net.glowstone.GlowServer.run(GlowServer.java:441)
    at net.glowstone.GlowServer.main(GlowServer.java:298)
```

Using Glowstone #220 from CI Server.

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/Glowstone/commit/442bc567fcfa2c180aac634b0630098ed3ca982d
