### ISSUE TITLE
Error loading entity: Sheep, Cow (NBT)

### ISSUE THREAD

**Issue by FastFelix771** [GlowstoneMC/Glowstone#347]
Glowstone build #223 from CI.

```
[WARNING] Error loading entity in GlowChunk{world=spigotworld,x=71,z=106}: Sheep
java.lang.IllegalArgumentException: Compound does not contain StringTag "TeamColor"
    at net.glowstone.util.nbt.CompoundTag.getTag(CompoundTag.java:272)
    at net.glowstone.util.nbt.CompoundTag.get(CompoundTag.java:266)
    at net.glowstone.util.nbt.CompoundTag.getString(CompoundTag.java:103)
    at net.glowstone.scoreboard.NbtScoreboardIoReader.registerTeam(NbtScoreboardIoReader.java:119)
    at net.glowstone.scoreboard.NbtScoreboardIoReader.registerTeams(NbtScoreboardIoReader.java:82)
    at net.glowstone.scoreboard.NbtScoreboardIoReader.readMainScoreboard(NbtScoreboardIoReader.java:27)
    at net.glowstone.io.nbt.NbtScoreboardIoService.readMainScoreboard(NbtScoreboardIoService.java:32)
    at net.glowstone.scoreboard.GlowScoreboardManager.getMainScoreboard(GlowScoreboardManager.java:24)
    at net.glowstone.entity.GlowLivingEntity.setHealth(GlowLivingEntity.java:452)
    at net.glowstone.io.entity.LivingEntityStore.load(LivingEntityStore.java:53)
    at net.glowstone.io.entity.CreatureStore.load(CreatureStore.java:13)
    at net.glowstone.io.entity.AgeableStore.load(AgeableStore.java:35)
    at net.glowstone.io.entity.SheepStore.load(SheepStore.java:23)
    at net.glowstone.io.entity.SheepStore.load(SheepStore.java:8)
    at net.glowstone.io.entity.EntityStorage.createEntity(EntityStorage.java:137)
    at net.glowstone.io.entity.EntityStorage.loadEntity(EntityStorage.java:129)
    at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:109)
    at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:147)
    at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:214)
    at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:247)
    at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:738)
    at net.glowstone.GlowWorld.<init>(GlowWorld.java:299)
    at net.glowstone.GlowServer.createWorld(GlowServer.java:1520)
    at net.glowstone.GlowServer.start(GlowServer.java:505)
    at net.glowstone.GlowServer.run(GlowServer.java:441)
    at net.glowstone.GlowServer.main(GlowServer.java:298)
```

**Comment by FastFelix771** [comment]
This probably appears to more, if not all (?) mobs.

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/Glowstone/commit/38645f64716c2a3e9807e88f457e9779424fd345
