### ISSUE TITLE
Skulls are still broken, other NBT tag this time.

### ISSUE THREAD

**Issue by FastFelix771** [GlowstoneMC/Glowstone#348]
```
[SEVERE] Error loading tile entity at GlowBlock{chunk=GlowChunk{world=spigotworld,x=80,z=106},x=1294,y=117,z=1711,type=SKULL,data=1}: Skull
java.lang.IllegalArgumentException: Compound does not contain StringTag "Signature"
    at net.glowstone.util.nbt.CompoundTag.getTag(CompoundTag.java:272)
    at net.glowstone.util.nbt.CompoundTag.get(CompoundTag.java:266)
    at net.glowstone.util.nbt.CompoundTag.getString(CompoundTag.java:103)
    at net.glowstone.entity.meta.profile.PlayerProfile.fromNBT(PlayerProfile.java:102)
    at net.glowstone.block.entity.TESkull.loadNbt(TESkull.java:35)
    at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:130)
    at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:147)
    at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:214)
    at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:247)
    at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:738)
    at net.glowstone.GlowWorld.<init>(GlowWorld.java:299)
    at net.glowstone.GlowServer.createWorld(GlowServer.java:1520)
    at net.glowstone.GlowServer.start(GlowServer.java:505)
    at net.glowstone.GlowServer.run(GlowServer.java:441)
    at net.glowstone.GlowServer.main(GlowServer.java:298)
2016/08/22 22:41:53 [INFORMATION] Preparing spawn for world: 38%
2016/08/22 22:41:54 [WARNUNG] Failed to look up profile
2016/08/22 22:41:54 [SEVERE] Error loading tile entity at GlowBlock{chunk=GlowChunk{world=spigotworld,x=82,z=111},x=1317,y=136,z=1780,type=SKULL,data=1}: Skull
java.lang.IllegalArgumentException: Compound does not contain StringTag "Signature"
    at net.glowstone.util.nbt.CompoundTag.getTag(CompoundTag.java:272)
    at net.glowstone.util.nbt.CompoundTag.get(CompoundTag.java:266)
    at net.glowstone.util.nbt.CompoundTag.getString(CompoundTag.java:103)
    at net.glowstone.entity.meta.profile.PlayerProfile.fromNBT(PlayerProfile.java:102)
    at net.glowstone.block.entity.TESkull.loadNbt(TESkull.java:35)
    at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:130)
    at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:147)
    at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:214)
    at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:247)
    at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:738)
    at net.glowstone.GlowWorld.<init>(GlowWorld.java:299)
    at net.glowstone.GlowServer.createWorld(GlowServer.java:1520)
    at net.glowstone.GlowServer.start(GlowServer.java:505)
    at net.glowstone.GlowServer.run(GlowServer.java:441)
    at net.glowstone.GlowServer.main(GlowServer.java:298)
2016/08/22 22:41:54 [WARNING] Failed to look up profile
2016/08/22 22:41:54 [SEVERE] Error loading tile entity at GlowBlock{chunk=GlowChunk{world=spigotworld,x=82,z=111},x=1317,y=137,z=1781,type=SKULL,data=1}: Skull
java.lang.NullPointerException
    at net.glowstone.entity.meta.profile.PlayerProfile.fromNBT(PlayerProfile.java:94)
    at net.glowstone.block.entity.TESkull.loadNbt(TESkull.java:35)
    at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:130)
    at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:147)
    at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:214)
    at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:247)
    at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:738)
    at net.glowstone.GlowWorld.<init>(GlowWorld.java:299)
    at net.glowstone.GlowServer.createWorld(GlowServer.java:1520)
    at net.glowstone.GlowServer.start(GlowServer.java:505)
    at net.glowstone.GlowServer.run(GlowServer.java:441)
    at net.glowstone.GlowServer.main(GlowServer.java:298)

```

Glowstone build #225 from CI.

**Comment by FastFelix771** [comment]
Sorry for the messed up formatting :octopus:
