### ISSUE TITLE
ItemFrames throws errors on chunk saves

### ISSUE THREAD

**Issue by FastFelix771** [GlowstoneMC/Glowstone#350]
Until a chunks try to save and unload and contains itemframes, this error will arise:

```
 [WARNING] Error saving GlowItemFrame in GlowChunk{world=spigotworld,x=-80,z=-59}
java.lang.NullPointerException
    at net.glowstone.entity.objects.GlowItemFrame.getFacingNumber(GlowItemFrame.java:53)
    at net.glowstone.entity.objects.GlowItemFrame.getFacingNumber(GlowItemFrame.java:283)
    at net.glowstone.io.entity.ItemFrameStore.save(ItemFrameStore.java:39)
    at net.glowstone.io.entity.ItemFrameStore.save(ItemFrameStore.java:9)
    at net.glowstone.io.entity.EntityStorage.save(EntityStorage.java:172)
    at net.glowstone.io.anvil.AnvilChunkIoService.write(AnvilChunkIoService.java:214)
    at net.glowstone.ChunkManager.performSave(ChunkManager.java:416)
    at net.glowstone.GlowChunk.unload(GlowChunk.java:211)
    at net.glowstone.ChunkManager.unloadOldChunks(ChunkManager.java:189)
    at net.glowstone.GlowWorld.saveWorld(GlowWorld.java:437)
    at net.glowstone.GlowWorld.pulse(GlowWorld.java:373)
    at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:139)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by FastFelix771** [comment]
`Error loading entity in GlowChunk{world=spigotworld,x=-7,z=13}: ItemFrame
java.lang.IllegalArgumentException: Compound does not contain IntTag "Facing"
    at net.glowstone.util.nbt.CompoundTag.getTag(CompoundTag.java:272)
    at net.glowstone.util.nbt.CompoundTag.get(CompoundTag.java:266)
    at net.glowstone.util.nbt.CompoundTag.getInt(CompoundTag.java:83)
    at net.glowstone.io.entity.ItemFrameStore.createEntity(ItemFrameStore.java:17)
    at net.glowstone.io.entity.ItemFrameStore.createEntity(ItemFrameStore.java:9)
    at net.glowstone.io.entity.EntityStorage.createEntity(EntityStorage.java:136)
    at net.glowstone.io.entity.EntityStorage.loadEntity(EntityStorage.java:129)
    at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:109)
    at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:147)
    at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:214)
    at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:247)
    at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:738)
    at net.glowstone.GlowWorld.<init>(GlowWorld.java:299)
    at net.glowstone.GlowServer.createWorld(GlowServer.java:1520)
    at net.glowstone.GlowServer.createWorld(GlowServer.java:92)
    at org.bukkit.Bukkit.createWorld(Bukkit.java:485)
    at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:447)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:422)
    at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:725)
    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:310)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:427)
    at net.glowstone.GlowServer.enablePlugins(GlowServer.java:819)
    at net.glowstone.GlowServer.start(GlowServer.java:516)
    at net.glowstone.GlowServer.run(GlowServer.java:441)
    at net.glowstone.GlowServer.main(GlowServer.java:298)`

Doesnt seem to work :/

**Comment by aramperes** [comment]
@FastFelix771 

> java.lang.IllegalArgumentException: Compound does not contain IntTag "Facing"

That's an issue with the item frame in question, not with Glowstone. The facing tag is required, and it cannot be optional (it directs the face of the item frame). 

It's possible that you imported the world containing the item frame, loaded it with an earlier version of Glowstone (before that commit), and the data was lost when saving the world. You should re-import the world from Paper directly. As I said before, **do not import worlds between Glowstone versions**, especially when there are NBT/Chunk IO changes.

**Comment by aramperes** [comment]
@FastFelix771 https://github.com/GlowstoneMC/Glowstone/commit/3996cd3d20846a7ebed1674d72c6185afbc03f6a should fix your issues, let me know if more problems arise.
