### ISSUE TITLE
Chunk compression issue (GZIP)

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#369]
Occasionally, chunks will fail to decompress when reading/populating chunks. This is one of those stacktraces:

```
java.util.zip.ZipException: Not in GZIP format
    at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
    at java.util.zip.GZIPInputStream.<init>(Unknown Source)
    at java.util.zip.GZIPInputStream.<init>(Unknown Source)
    at net.glowstone.io.anvil.RegionFile.getChunkDataInputStream(RegionFile.java:203)
    at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:68)
    at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:147)
    at net.glowstone.GlowChunk.load(GlowChunk.java:188)
    at net.glowstone.generator.populators.StructurePopulator.populate(StructurePopulator.java:36)
    at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:232)
    at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:247)
    at net.glowstone.entity.GlowPlayer.streamBlocks(GlowPlayer.java:704)
    at net.glowstone.entity.GlowPlayer.pulse(GlowPlayer.java:570)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
    at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
    at java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source)
    at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
    at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
    at java.util.stream.ReferencePipeline.forEach(Unknown Source)
    at net.glowstone.GlowWorld.pulsePlayers(GlowWorld.java:483)
    at net.glowstone.GlowWorld.pulse(GlowWorld.java:364)
    at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:139)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by Paulomart** [comment]
This is related to any other errors occurring during reading chunks. I think there is some unsafe hacking going on, @mastercoms may know more. It also may have to do with not resetting the stream or resetting it.

**Comment by picknchew** [comment]
There are also stack traces like this. 
![m1yyjj4 1](https://cloud.githubusercontent.com/assets/3619860/18256501/2f8af7b4-7384-11e6-814a-7fc504560dd9.png)
They appear on startup after a forced shutdown.

**Comment by mastercoms** [comment]
We did a big cleanup of `RegionFile` just now (https://github.com/GlowstoneMC/Glowstone/commit/de89225bc3cb256be34e8b5a2c79fbbafceb1f0f).

Perhaps it did something to fix this bug unintentionally.
