### ISSUE TITLE
/title command throws NPE when executing invalid JSON

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#392]
```
15:11:25 [GRAVE] Exception while executing command: /title yKuriDev_ title testing
org.bukkit.command.CommandException: Unhandled exception executing 'title yKuriDev_ title testing' in net.glowstone.command.TitleCommand(title)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:197)
        at net.glowstone.GlowServer.dispatchCommand(GlowServer.java:1195)
        at net.glowstone.entity.GlowPlayer.lambda$chat$7(GlowPlayer.java:1785)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at net.glowstone.scheduler.GlowTask.run(GlowTask.java:167)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:152)
        at net.glowstone.scheduler.GlowScheduler.lambda$start$0(GlowScheduler.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at net.md_5.bungee.api.chat.BaseComponent.toPlainText(BaseComponent.java:130)
        at net.glowstone.net.message.play.game.TitleMessage.fromTitle(TitleMessage.java:46)
        at net.glowstone.entity.GlowPlayer.sendTitle(GlowPlayer.java:2155)
        at net.glowstone.command.TitleCommand.execute(TitleCommand.java:132)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188)
        ... 14 more
```

**Comment by aramperes** [comment]
I think the current implementation of the `/title` command only supports Raw JSON components instead of plain text. This definitely needs to be reworked.

**Comment by mastercoms** [comment]
No, the title command is supposed to use Raw JSON. http://minecraft.gamepedia.com/Commands#Raw_JSON_text

However, the syntax can be made better to fit with vanilla syntax.

But under no circumstance should we allow for plain text. That is a command for plugins to add.

**Comment by aramperes** [comment]
Yes but it should fallback to plain text if the given string is not valid JSON, afaik.

Edit: It appears not, you were right. TIL. It should warn you though, instead of throwing an NPE.

**Comment by mastercoms** [comment]
Vanilla doesn't do this, I'm pretty sure. I'm not sure if deviating from that behavior should be done.

**Comment by ethsmith** [comment]
@mastercoms Is there harm in deviating from that original behavior?

**Comment by mastercoms** [comment]
There might be some weird behavior if a script is expecting the command to fail because of poor syntax.
