### ISSUE TITLE
Loading chunks

### ISSUE THREAD

**Issue by Aslaak** [GlowstoneMC/Glowstone#399]
Hello,
when I teleport myself in the last version, I often got this error:

```
2016/12/22 21:55:03 [GRAVE] Error while loading chunk (3,-10)
java.io.IOException: Unknown version: 0
	at net.glowstone.io.anvil.RegionFile.getChunkDataInputStream(RegionFile.java:222)
	at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:68)
	at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:147)
	at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:214)
	at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:247)
	at net.glowstone.entity.GlowPlayer.streamBlocks(GlowPlayer.java:702)
	at net.glowstone.entity.GlowPlayer.pulse(GlowPlayer.java:569)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at net.glowstone.GlowWorld.pulsePlayers(GlowWorld.java:485)
	at net.glowstone.GlowWorld.pulse(GlowWorld.java:366)
	at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:139)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

I don't really know if it comes from glowstone or a plugin, but I think it's from glowstone because I only have a custom plugin which don't work with chunks...
I hope it will help you !

**Comment by gdude2002** [comment]
Just so you know, I edited your ticket to include the error directly. Hastebin deletes pastes quickly.

I've seen this one a lot too, even on the test server. We're aware of it, but I think only @momothereal or @mastercoms will be able to tell you what the issue actually is.

**Comment by Aslaak** [comment]
oh sorry for hastebin :c 

it's not very important and I don't really care about it it's not urgent :)

**Comment by mastercoms** [comment]
Duplicate of #199

**Comment by aramperes** [comment]
@Aslaak was this world ported from Vanilla/Spigot, or is it a fresh Glowstone world?

e: also level seed would be appreciated :)

**Comment by Aslaak** [comment]
yes it's a fresh glowstone world, the level seed is : -1477976409506853065
