### ISSUE TITLE
Plugin#saveDefaultconfig() causing IllegalArgumentException when file doesn't exist 

### ISSUE THREAD

**Issue by hugo4715** [GlowstoneMC/Glowstone#407]
From the spigot doc: http://imgur.com/a/uWvW9
https://hub.spigotmc.org/javadocs/spigot/
but when it try my plugin, i got an Exception
```
The embedded resource 'config.yml' cannot be found in plugins\plugin-1.0.jar
at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:202)
	at org.bukkit.plugin.java.JavaPlugin.saveDefaultConfig(JavaPlugin.java:189)
	at tk.hugo4715.plugin.MyPlugin.onEnable(MyPlugin.java:TheLine)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:415)
	at net.glowstone.GlowServer.enablePlugins(GlowServer.java:787)
	at net.glowstone.GlowServer.reload(GlowServer.java:839)
	at org.bukkit.Bukkit.reload(Bukkit.java:557)
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:50)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188)
	at net.glowstone.GlowServer.dispatchCommand(GlowServer.java:1207)
	at net.glowstone.ConsoleManager$CommandTask.run(ConsoleManager.java:284)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.glowstone.scheduler.GlowTask.run(GlowTask.java:167)
	at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:152)
	at net.glowstone.scheduler.GlowScheduler.lambda$start$0(GlowScheduler.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by gdude2002** [comment]
Are you actually shading a `config.yml` into your plugin jar?

**Comment by hugo4715** [comment]
No, but in the documentation of the spigot api it says:
`Saves the raw contents of the default config.yml file to the location retrievable by getConfig(). If there is no default config.yml embedded in the plugin, an empty config.yml file is saved. This should fail silently if the config.yml already exists.`
Some plugin (not a lot) could be crashing because of that

**Comment by gdude2002** [comment]
Ah, okay, that's kind of important information, 😛

**Comment by aramperes** [comment]
@hugo4715 this is intended behavior, you can trace back this error to Bukkit itself rather than Glowstone. This method will create a `config.yml` file in the plugin's folder, not in the JAR. You need to have a `config.yml` in your plugin JAR to use this method.

Source: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/plugin/java/JavaPlugin.java#189,202

**Comment by hugo4715** [comment]
That's strange, so it's just a mistake in the documentation?

**Comment by aramperes** [comment]
@hugo4715 
I guess so. You might want to poke Spigot for this issue, they maintain Bukkit.

**Comment by hugo4715** [comment]
I may do it later, bye.

Thanks a lot :p
