### ISSUE TITLE
Error on download libs.

### ISSUE THREAD

**Issue by Mepth** [GlowstoneMC/Glowstone#412]
WTF

```
16:37:44 [WARNING] Failed to download: sqlite-jdbc 3.15.1
java.io.FileNotFoundException: https://repo.glowstone.net/service/local/repositories/central/content/org/xerial/sqlite-jdbc/3.15.1/sqlite-jdbc-3.15.1.jar
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at net.glowstone.util.LibraryManager$LibraryDownloader.run(LibraryManager.java:85)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
16:37:44 [WARNING] Failed to download: slf4j-jdk14 1.7.15
java.io.FileNotFoundException: https://repo.glowstone.net/service/local/repositories/central/content/org/slf4j/slf4j-jdk14/1.7.15/slf4j-jdk14-1.7.15.jar
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at net.glowstone.util.LibraryManager$LibraryDownloader.run(LibraryManager.java:85)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
16:37:44 [WARNING] Failed to download: mysql-connector-java 5.1.39
java.io.FileNotFoundException: https://repo.glowstone.net/service/local/repositories/central/content/mysql/mysql-connector-java/5.1.39/mysql-connector-java-5.1.39.jar
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at net.glowstone.util.LibraryManager$LibraryDownloader.run(LibraryManager.java:85)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

---

*Edited by `gdude2002` for formatting*

**Comment by thelex0** [comment]
++

**Comment by gdude2002** [comment]
This is a known issue. We're having some problems with our Maven server at the moment. 

If you restart Glowstone, you should be fine. If there are plugins that require these libraries, then you can download them from Maven Central.

**Comment by gdude2002** [comment]
@thelex337 Please use the Reactions feature at the top right of the ticket instead of commenting with `++` or `+1`

**Comment by thelex0** [comment]
why when I download source code 
dont compile

**Comment by gdude2002** [comment]
@thelex337 Please make a new ticket if you're having a different issue. 

That said, it should compile just fine - the latest commit [builds just fine for us](http://bamboo.gserv.me/browse/GSPP-SRV/latest)

**Comment by Mepth** [comment]
```
4:57:52 [SEVERE] Error while loading chunk (-10,9)
java.io.IOException: Invalid length: 3307676 > 4096
        at net.glowstone.io.anvil.RegionFile.getChunkDataInputStream(RegionFile.java:208)
        at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:68)
        at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:147)
        at net.glowstone.GlowChunk.load(GlowChunk.java:188)
        at net.glowstone.GlowChunk.load(GlowChunk.java:181)
        at net.glowstone.GlowChunk.getSection(GlowChunk.java:282)
        at net.glowstone.GlowChunk.getType(GlowChunk.java:322)
        at net.glowstone.block.GlowBlock.getTypeIdNoCache(GlowBlock.java:192)
        at net.glowstone.block.GlowBlock.getType(GlowBlock.java:178)
        at net.glowstone.entity.GlowLivingEntity.pulse(GlowLivingEntity.java:177)
        at net.glowstone.entity.GlowAgeable.pulse(GlowAgeable.java:48)
        at net.glowstone.GlowWorld.pulse(GlowWorld.java:379)
        at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:139)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
14:57:52 [SEVERE] Error while loading chunk (-10,8)
java.io.IOException: Unknown version: 0
        at net.glowstone.io.anvil.RegionFile.getChunkDataInputStream(RegionFile.java:222)
        at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:68)
        at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:147)
        at net.glowstone.GlowChunk.load(GlowChunk.java:188)
        at net.glowstone.GlowChunk.load(GlowChunk.java:181)
        at net.glowstone.GlowChunk.getSection(GlowChunk.java:282)
        at net.glowstone.GlowChunk.getType(GlowChunk.java:322)
        at net.glowstone.GlowWorld.getBlockTypeIdAt(GlowWorld.java:1010)
        at net.glowstone.entity.GlowEntity.isTouchingMaterial(GlowEntity.java:659)
        at net.glowstone.entity.GlowLivingEntity.pulse(GlowLivingEntity.java:191)
        at net.glowstone.entity.GlowAgeable.pulse(GlowAgeable.java:48)
        at net.glowstone.GlowWorld.pulse(GlowWorld.java:379)
        at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:139)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

---

*Edited by `gdude2002` for formatting*

**Comment by gdude2002** [comment]
You should comment on #256 about that, particularly whether it actually causes you any problems. 

My patience is beginning to wear a little. Please search issues for problems you have that may already be being discussed, and keep each issue separate.

**Comment by gdude2002** [comment]
@mastercoms has discovered the root problem of the library download issue. We're looking into the best way around it now.

**Comment by kamcio96** [comment]
Uhhh, guys, how old are you?

@gdude2002 what about remove ssl and use separated host for libs? ```http://libs.glowstone.net/org/xerial/sqlite-jdbc/3.15.1/sqlite-jdbc-3.15.1.jar```

**Comment by mastercoms** [comment]
Fixed
