### ISSUE TITLE
Placing a block throws a NullPointerException

### ISSUE THREAD

**Issue by MrPowerGamerBR** [GlowstoneMC/Glowstone#423]
**Glowstone build:** I'm using a compiled from source build, I can't download the latest build right now because I'm travelling, so... ```git reset --hard b5e0a6d9b589eb93c47a165b45d0a0b5c49be8de``` (Latest commit from this repo)

Placing a block throws an NullPointerException, tested in Survival and Creative. After relogging, the block goes away.

```
19:10:19 [GRAVE] Error while handling BlockPlacementMessage(x=47, y=67, z=35, direction=3, hand=0, cursorX=0.6663003, cursorY=0.22557133, cursorZ=1.0) (handler: BlockPlacementHandler)
java.lang.NullPointerException
        at net.glowstone.net.handler.play.player.BlockPlacementHandler.handle(BlockPlacementHandler.java:105)
        at net.glowstone.net.handler.play.player.BlockPlacementHandler.handle(BlockPlacementHandler.java:24)
        at com.flowpowered.network.session.BasicSession.handleMessage(BasicSession.java:80)
        at com.flowpowered.network.session.BasicSession.messageReceived(BasicSession.java:139)
        at net.glowstone.net.GlowSession.pulse(GlowSession.java:472)
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(Unknown Source)
        at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:144)
        at net.glowstone.scheduler.GlowScheduler.lambda$start$0(GlowScheduler.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by MrPowerGamerBR** [comment]
Also happens with spawn eggs
