### ISSUE TITLE
Incorrect NBT Tile Entity IDs

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone#426]
```java
10:29:17 [SEVERE] Error loading tile entity at GlowBlock{chunk=GlowChunk{world=world,x=-9,z=6},x=-135,y=56,z=104,type=CHEST,data=5}: Chest
java.lang.IllegalArgumentException: Expected tile entity id of chest, got Chest
        at net.glowstone.block.entity.TileEntity.loadNbt(TileEntity.java:73)
        at net.glowstone.block.entity.TEContainer.loadNbt(TEContainer.java:33)
        at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:135)
        at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:147)
        at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:214)
        at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:247)
        at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:768)
        at net.glowstone.GlowWorld.<init>(GlowWorld.java:314)
        at net.glowstone.GlowServer.createWorld(GlowServer.java:1515)
        at net.glowstone.GlowServer.start(GlowServer.java:501)
        at net.glowstone.GlowServer.run(GlowServer.java:432)
        at net.glowstone.GlowServer.main(GlowServer.java:305)
10:29:17 [SEVERE] Error loading tile entity at GlowBlock{chunk=GlowChunk{world=world,x=-9,z=6},x=-133,y=56,z=104,type=MOB_SPAWNER,data=0}: MobSpawner
java.lang.IllegalArgumentException: Expected tile entity id of mob_spawner, got MobSpawner
        at net.glowstone.block.entity.TileEntity.loadNbt(TileEntity.java:73)
        at net.glowstone.block.entity.TEMobSpawner.loadNbt(TEMobSpawner.java:23)
        at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:135)
        at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:147)
        at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:214)
        at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:247)
        at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:768)
        at net.glowstone.GlowWorld.<init>(GlowWorld.java:314)
        at net.glowstone.GlowServer.createWorld(GlowServer.java:1515)
        at net.glowstone.GlowServer.start(GlowServer.java:501)
        at net.glowstone.GlowServer.run(GlowServer.java:432)
        at net.glowstone.GlowServer.main(GlowServer.java:305)
10:29:17 [SEVERE] Error loading tile entity at GlowBlock{chunk=GlowChunk{world=world,x=-9,z=6},x=-131,y=56,z=105,type=CHEST,data=4}: Chest
java.lang.IllegalArgumentException: Expected tile entity id of chest, got Chest
        at net.glowstone.block.entity.TileEntity.loadNbt(TileEntity.java:73)
        at net.glowstone.block.entity.TEContainer.loadNbt(TEContainer.java:33)
        at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:135)
        at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:147)
        at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:214)
        at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:247)
        at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:768)
        at net.glowstone.GlowWorld.<init>(GlowWorld.java:314)
        at net.glowstone.GlowServer.createWorld(GlowServer.java:1515)
        at net.glowstone.GlowServer.start(GlowServer.java:501)
        at net.glowstone.GlowServer.run(GlowServer.java:432)
        at net.glowstone.GlowServer.main(GlowServer.java:305)
```

**Comment by aramperes** [comment]
Relevant list of the new block entity IDs: http://minecraft.gamepedia.com/Chunk_format#Block_entity_format

**Comment by mastercoms** [comment]
Apparently they're `minecraft:id`, so `minecraft:chest`, etc.
