### ISSUE TITLE
Fall damage and water interactions  

### ISSUE THREAD

**Issue by adlradlr** [GlowstoneMC/Glowstone#427]
Glowstone build: 359

- Jumping into water from any height gives fall damage. Jumping from a block into an adjacent water block (1 deep) at the same level on the y axis gives 1/2 heart of fall damage, the higher the fall, the more fall damage is given. (Given enough height, this is also the case when walking off, instead of jumping) 

- Jumping from a block into a deeper body of water, works as expected initially, until I come into contact with a block, where the fall damage is then applied. (To test this I jumped from a height into an ocean, and floated down to the bottom where I would then be killed by the fall damage once reaching the bottom)

- About 50% of the time I am able to take a varying amount (1/2 - 3/2 hearts) of damage from jumping out of a water block onto an adjacent block. (edit: After further testing, this is caused by jumping out of water at least 2 blocks deep, now able to reproduce 100% of the time.)
```
09:54:36 [SEVERE] Error while handling PlayerUpdateMessage(onGround=true) (handler: PlayerUpdateHandler)
java.lang.NullPointerException
        at net.glowstone.entity.GlowPlayer.getDisplayName(GlowPlayer.java:1004)
        at net.glowstone.entity.GlowLivingEntity.setHealth(GlowLivingEntity.java:572)
        at net.glowstone.entity.GlowPlayer.setHealth(GlowPlayer.java:1319)
        at net.glowstone.entity.GlowLivingEntity.damage(GlowLivingEntity.java:653)
        at net.glowstone.entity.GlowLivingEntity.damage(GlowLivingEntity.java:606)
        at net.glowstone.entity.GlowPlayer.damage(GlowPlayer.java:439)
        at net.glowstone.entity.GlowPlayer.damage(GlowPlayer.java:415)
        at net.glowstone.entity.GlowLivingEntity.setOnGround(GlowLivingEntity.java:826)
        at net.glowstone.entity.GlowPlayer.setOnGround(GlowPlayer.java:1183)
        at net.glowstone.net.handler.play.player.PlayerUpdateHandler.handle(PlayerUpdateHandler.java:99)
        at net.glowstone.net.handler.play.player.PlayerUpdateHandler.handle(PlayerUpdateHandler.java:21)
        at com.flowpowered.network.session.BasicSession.handleMessage(BasicSession.java:80)
        at com.flowpowered.network.session.BasicSession.messageReceived(BasicSession.java:139)
        at net.glowstone.net.GlowSession.pulse(GlowSession.java:472)
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(Unknown Source)
        at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:144)
        at net.glowstone.scheduler.GlowScheduler.lambda$start$0(GlowScheduler.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
09:54:48 [SEVERE] Error occurred while pulsing world world
java.lang.NullPointerException
        at net.glowstone.entity.GlowPlayer.getDisplayName(GlowPlayer.java:1004)
        at net.glowstone.entity.GlowLivingEntity.setHealth(GlowLivingEntity.java:572)
        at net.glowstone.entity.GlowPlayer.setHealth(GlowPlayer.java:1319)
        at net.glowstone.entity.GlowLivingEntity.damage(GlowLivingEntity.java:653)
        at net.glowstone.entity.GlowLivingEntity.damage(GlowLivingEntity.java:606)
        at net.glowstone.entity.GlowPlayer.damage(GlowPlayer.java:439)
        at net.glowstone.entity.GlowLivingEntity.pulse(GlowLivingEntity.java:181)
        at net.glowstone.entity.GlowHumanEntity.pulse(GlowHumanEntity.java:145)
        at net.glowstone.entity.GlowPlayer.pulse(GlowPlayer.java:507)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at net.glowstone.GlowWorld.pulsePlayers(GlowWorld.java:513)
        at net.glowstone.GlowWorld.pulse(GlowWorld.java:394)
        at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:139)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
09:54:57 [INFO] pandanoir [/127.0.0.1:53568] lost connection
```

**Comment by adlradlr** [comment]
Not sure if related or Glowstone feature, but if I don't respawn immediately I get disconnected ~20s after dying.

**Comment by aramperes** [comment]
Hey, thanks for the report.

Would you mind reporting the death/respawn bug in another issue? It would make it easier to organize our workflow to fix them separately.

**Comment by mastercoms** [comment]
I think this was fixed in https://github.com/GlowstoneMC/Glowstone/commit/8a57f8a2b63767925ccd85178cec0631c20bf607, could you test it out?

**Comment by adlradlr** [comment]
Glowstone build #361 

I can no longer reproduce any of the issues now.
