### ISSUE TITLE
Exception when generating world, invalid data value

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#455]
Glowstone build: `#445`

When generating the world, this exception was thrown at me:

```
[SEVERE] Error while executing GlowTask{id=2, plugin=null, sync=false:net.glowstone.scheduler.PulseTask@d675f9f}
java.lang.IllegalArgumentException: value (16) must not be greater than 15
        at net.glowstone.util.VariableValueArray.set(VariableValueArray.java:66)
        at net.glowstone.chunk.ChunkSection.setType(ChunkSection.java:347)
        at net.glowstone.chunk.GlowChunk.setMetaData(GlowChunk.java:458)
        at net.glowstone.block.GlowBlock.setTypeIdAndData(GlowBlock.java:231)
        at net.glowstone.block.GlowBlock.setType(GlowBlock.java:212)
        at net.glowstone.block.blocktype.BlockLiquid.flow(BlockLiquid.java:192)
        at net.glowstone.block.blocktype.BlockLiquid.calculateTarget(BlockLiquid.java:156)
        at net.glowstone.block.blocktype.BlockLiquid.calculateFlow(BlockLiquid.java:132)
        at net.glowstone.block.blocktype.BlockLiquid.updatePhysics(BlockLiquid.java:249)
        at net.glowstone.block.blocktype.BlockLiquid.receivePulse(BlockLiquid.java:112)
        at net.glowstone.scheduler.PulseTask.run(PulseTask.java:59)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.glowstone.scheduler.GlowTask.run(GlowTask.java:167)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

I was using the default world generator (no GPU).

**Comment by mastercoms** [comment]
By the way, there is no GPU world gen. There is only an OpenCL API in Glowstone now that the server and plugins can use.

**Comment by mastercoms** [comment]
It seems like this issue is caused by water flowing into another chunk.

**Comment by VaiTon** [comment]
Is the pulse method called during the world generation?

**Comment by aramperes** [comment]
I've never been able to reproduce this issue since then, I suspect it may have been caused by world corruption. Has anyone experienced this too?

**Comment by mastercoms** [comment]
I have never encountered this issue.
