### ISSUE TITLE
NullPointerException in GlowMetaBook

### ISSUE THREAD

**Issue by minecrafter** [GlowstoneMC/Glowstone#466]
Title: NullPointerException in GlowMetaBook

Glowstone build: #468

When I tested BuycraftX on Glowstone, I came across the error below relating to `GlowMetaBook`. The [relevant code](https://github.com/BuycraftPlugin/BuycraftX/blob/master/bukkit/src/main/java/net/buycraft/plugin/bukkit/gui/CategoryViewGUI.java#L250) works fine with Spigot 1.11.2, so this appears to be an issue with Glowstone.

Expected:

No error, GUI updates successfully.

Actual:

Exception as mentioned below.

Reproduce:

1. Install BuycraftX 10.2 (latest version) onto a fresh Glowstone server
2. Set your secret key from the console
3. Observe error after several seconds of the key being verified

---

```
06:58:13 [SEVERE] [BuycraftX] Error while executing GlowTask{id=5880, plugin=BuycraftX v10.2, sync=true: net.buycraft.plugin.bukkit.tasks.GUIUpdateTask@7cfe25e8}
java.lang.NullPointerException
	at net.glowstone.inventory.GlowMetaBook.getGeneration(GlowMetaBook.java:147)
	at net.glowstone.inventory.GlowMetaBook.<init>(GlowMetaBook.java:36)
	at net.glowstone.inventory.GlowItemFactory.makeMeta(GlowItemFactory.java:115)
	at net.glowstone.inventory.GlowItemFactory.asMetaFor(GlowItemFactory.java:70)
	at org.bukkit.inventory.ItemStack.setItemMeta0(ItemStack.java:604)
	at org.bukkit.inventory.ItemStack.setItemMeta(ItemStack.java:590)
	at net.buycraft.plugin.bukkit.gui.CategoryViewGUI$GUIImpl.update(CategoryViewGUI.java:250)
	at net.buycraft.plugin.bukkit.gui.CategoryViewGUI$GUIImpl.<init>(CategoryViewGUI.java:143)
	at net.buycraft.plugin.bukkit.gui.CategoryViewGUI.doUpdate(CategoryViewGUI.java:91)
	at net.buycraft.plugin.bukkit.gui.CategoryViewGUI.update(CategoryViewGUI.java:81)
	at net.buycraft.plugin.bukkit.tasks.GUIUpdateTask.run(GUIUpdateTask.java:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.glowstone.scheduler.GlowTask.run(GlowTask.java:167)
	at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:152)
	at net.glowstone.scheduler.GlowScheduler.lambda$start$0(GlowScheduler.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by aramperes** [comment]
Could you test the plugin with 59b7706dbf421df70e2186ff49b172251323a4d8?

**Comment by minecrafter** [comment]
This issue is now resolved, but I've now found another:

Try using `/buy` with more than one category.

Here's Glowstone (broken):

![](https://screenshot.today/04-25-2017-15-35-01.png)

Here's Spigot (working):

![](https://screenshot.today/04-25-2017-15-37-08.png)

Specifically, these items are all books, but they have different display names. [This code](https://github.com/BuycraftPlugin/BuycraftX/blob/master/bukkit/src/main/java/net/buycraft/plugin/bukkit/gui/ViewCategoriesGUI.java#L61) generates the items for that inventory.

**Comment by aramperes** [comment]
Ok, I will take a look at that.

**Comment by aramperes** [comment]
Could you confirm that e77de71bd49ce31d4460870b7c40e9d9bc49b012 fixes the issue with `addItem()`? I did not test it.

**Comment by mastercoms** [comment]
Closing due to probable fix and inactivity.
