### ISSUE TITLE
NPE when spawning Ender Dragon in End populator

### ISSUE THREAD

**Issue by satoshinm** [GlowstoneMC/Glowstone#482]
Fresh server install of Glowstone build 520, received this error during chunk generation of the end:

```
14:47:25 [INFO] This server is running Glowstone version 2017.5.0.52-SNAPSHOT-MC1.11.2 (Implementing API version 1.11.2-R0.1-SNAPSHOT)
[...]
14:47:53 [INFO] Preparing spawn for world_the_end...
14:47:54 [SEVERE] Error while populating chunk (0,0)
java.lang.NullPointerException
	at java.lang.Class.isAssignableFrom(Native Method)
	at net.glowstone.GlowWorld.spawn(GlowWorld.java:1285)
	at net.glowstone.GlowWorld.spawn(GlowWorld.java:1274)
	at net.glowstone.GlowWorld.spawnEntity(GlowWorld.java:1383)
	at net.glowstone.generator.populators.TheEndPopulator.populate(TheEndPopulator.java:27)
	at net.glowstone.chunk.ChunkManager.populateChunk(ChunkManager.java:234)
	at net.glowstone.chunk.ChunkManager.forcePopulation(ChunkManager.java:249)
	at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:769)
	at net.glowstone.GlowWorld.setSpawnLocation(GlowWorld.java:729)
	at net.glowstone.GlowWorld.<init>(GlowWorld.java:322)
	at net.glowstone.GlowServer.createWorld(GlowServer.java:1657)
	at net.glowstone.GlowServer.start(GlowServer.java:626)
	at net.glowstone.GlowServer.run(GlowServer.java:452)
	at net.glowstone.GlowServer.main(GlowServer.java:322)
14:47:54 [INFO] Preparing spawn for world_the_end: 87%
14:47:54 [INFO] Preparing spawn for world_the_end: done
````

From reviewing the code, it looks like clazz is null here:

```java
    public GlowEntity spawn(Location location, Class<? extends GlowEntity> clazz, SpawnReason reason) throws IllegalArgumentException {
        GlowEntity entity = null;

        if (TNTPrimed.class.isAssignableFrom(clazz)) {
            entity = new GlowTNTPrimed(location, null);
        }
```

First I've seen this error today, maybe introduced by https://github.com/GlowstoneMC/Glowstone/commit/4c9f326456643eb3bbcfea8cf87c2c2fa7c6dbb8 Spawn the ender dragon in the end?

**Comment by aramperes** [comment]
Likely because it is attempting to spawn an EntityType that has not been implemented and registered in the [EntityRegistry](https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/entity/EntityRegistry.java#L33).

**Comment by mastercoms** [comment]
Ah, I assumed ender dragon was implemented. Whoops.

**Comment by satoshinm** [comment]
For now should https://github.com/GlowstoneMC/Glowstone/commit/4c9f326456643eb3bbcfea8cf87c2c2fa7c6dbb8 be reverted?

**Comment by mastercoms** [comment]
I think it would be better for ender dragon to be added.
