### ISSUE TITLE
NPE at org.bukkit.material.Sign.getFacing(Sign.java:147)

### ISSUE THREAD

**Issue by satoshinm** [GlowstoneMC/Glowstone#484]
Load the world https://github.com/satoshinm/SignTestPlugin/blob/master/data/npe-getrelative166/r.0.0.mca, install this test plugin: https://github.com/satoshinm/SignTestPlugin, then login and place and break a block at (2, 77, 0). These errors will occur:

```
block = GlowBlock{chunk=GlowChunk{world=world,x=0,z=0},x=2,y=77,z=0,type=WALL_SIGN,data=0}
20:05:39 [INFO] materialData.toString() failed: java.lang.NullPointerException
20:05:39 [WARNING] java.lang.NullPointerException
20:05:39 [WARNING] 	at org.bukkit.material.Sign.getFacing(Sign.java:147)
20:05:39 [WARNING] 	at org.bukkit.material.Sign.toString(Sign.java:253)
20:05:39 [WARNING] 	at java.lang.String.valueOf(String.java:2994)
20:05:39 [WARNING] 	at java.lang.StringBuilder.append(StringBuilder.java:131)
20:05:39 [WARNING] 	at io.github.satoshinm.SignTestPlugin.SampleBlockListener.dumpSign(SampleBlockListener.java:39)
20:05:39 [WARNING] 	at io.github.satoshinm.SignTestPlugin.SampleBlockListener.onPlayerInteract(SampleBlockListener.java:27)
20:05:39 [WARNING] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source)
20:05:39 [WARNING] 	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
20:05:39 [WARNING] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
20:05:39 [WARNING] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
20:05:39 [WARNING] 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:525)
20:05:39 [WARNING] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:510)
20:05:39 [WARNING] 	at net.glowstone.EventFactory.lambda$callEvent$0(EventFactory.java:48)
20:05:39 [WARNING] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20:05:39 [WARNING] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20:05:39 [WARNING] 	at net.glowstone.scheduler.GlowScheduler.scheduleInTickExecution(GlowScheduler.java:126)
20:05:39 [WARNING] 	at net.glowstone.EventFactory.callEvent(EventFactory.java:49)
20:05:39 [WARNING] 	at net.glowstone.EventFactory.onPlayerInteract(EventFactory.java:155)
20:05:39 [WARNING] 	at net.glowstone.net.handler.play.player.DiggingHandler.handle(DiggingHandler.java:61)
20:05:39 [WARNING] 	at net.glowstone.net.handler.play.player.DiggingHandler.handle(DiggingHandler.java:35)
20:05:39 [WARNING] 	at com.flowpowered.network.session.BasicSession.handleMessage(BasicSession.java:80)
20:05:39 [WARNING] 	at com.flowpowered.network.session.BasicSession.messageReceived(BasicSession.java:139)
20:05:39 [WARNING] 	at net.glowstone.net.GlowSession.pulse(GlowSession.java:472)
20:05:39 [WARNING] 	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649)
20:05:39 [WARNING] 	at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
20:05:39 [WARNING] 	at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:144)
20:05:39 [WARNING] 	at net.glowstone.scheduler.GlowScheduler.lambda$start$0(GlowScheduler.java:83)
20:05:39 [WARNING] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20:05:39 [WARNING] 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
20:05:39 [WARNING] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
20:05:39 [WARNING] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
20:05:39 [WARNING] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
20:05:39 [WARNING] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
20:05:39 [WARNING] 	at java.lang.Thread.run(Thread.java:748)
20:05:39 [INFO] getAttachedFace = null
20:05:39 [INFO] getFacing exception: java.lang.NullPointerException
20:05:39 [WARNING] java.lang.NullPointerException
20:05:39 [WARNING] 	at org.bukkit.material.Sign.getFacing(Sign.java:147)
20:05:39 [WARNING] 	at io.github.satoshinm.SignTestPlugin.SampleBlockListener.dumpSign(SampleBlockListener.java:55)
20:05:39 [WARNING] 	at io.github.satoshinm.SignTestPlugin.SampleBlockListener.onPlayerInteract(SampleBlockListener.java:27)
20:05:39 [WARNING] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source)
20:05:39 [WARNING] 	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
20:05:39 [WARNING] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
20:05:39 [WARNING] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
20:05:39 [WARNING] 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:525)
20:05:39 [WARNING] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:510)
20:05:39 [WARNING] 	at net.glowstone.EventFactory.lambda$callEvent$0(EventFactory.java:48)
20:05:39 [WARNING] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20:05:39 [WARNING] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20:05:39 [WARNING] 	at net.glowstone.scheduler.GlowScheduler.scheduleInTickExecution(GlowScheduler.java:126)
20:05:39 [WARNING] 	at net.glowstone.EventFactory.callEvent(EventFactory.java:49)
20:05:39 [WARNING] 	at net.glowstone.EventFactory.onPlayerInteract(EventFactory.java:155)
20:05:39 [WARNING] 	at net.glowstone.net.handler.play.player.DiggingHandler.handle(DiggingHandler.java:61)
20:05:39 [WARNING] 	at net.glowstone.net.handler.play.player.DiggingHandler.handle(DiggingHandler.java:35)
20:05:39 [WARNING] 	at com.flowpowered.network.session.BasicSession.handleMessage(BasicSession.java:80)
20:05:39 [WARNING] 	at com.flowpowered.network.session.BasicSession.messageReceived(BasicSession.java:139)
20:05:39 [WARNING] 	at net.glowstone.net.GlowSession.pulse(GlowSession.java:472)
20:05:39 [WARNING] 	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649)
20:05:39 [WARNING] 	at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
20:05:39 [WARNING] 	at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:144)
20:05:39 [WARNING] 	at net.glowstone.scheduler.GlowScheduler.lambda$start$0(GlowScheduler.java:83)
20:05:39 [WARNING] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20:05:39 [WARNING] 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
20:05:39 [WARNING] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
20:05:39 [WARNING] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
20:05:39 [WARNING] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
20:05:39 [WARNING] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
20:05:39 [WARNING] 	at java.lang.Thread.run(Thread.java:748)
20:05:39 [INFO] isWallSign? true
20:05:39 [INFO] getData (deprecated) = 0
```

The plugin is simply calling toString on MaterialData, and getFacing() on Sign, both hit a NullPointerException in Glowkit src/main/java/org/bukkit/material/Sign.java:

```java
            return getAttachedFace().getOppositeFace();
```

getAttachedFace() will return null if is a wall sign without a valid data value:

```java
    public BlockFace getAttachedFace() {
        if (isWallSign()) {
            byte data = getData();

            switch (data) {
            case 0x2:
                return BlockFace.SOUTH;

            case 0x3:
                return BlockFace.NORTH;

            case 0x4:
                return BlockFace.EAST;

            case 0x5:
                return BlockFace.WEST;
            }

            return null;
        } else {
            return BlockFace.DOWN;
        }
    }
```

Not sure where this should be fixed, Glowkit or Glowstone..

**Comment by satoshinm** [comment]
Possible fix (tested locally but I'll need to research the glowkit patching system to submit a pull request), adding a straightforward null check in Glowkit getFacing():

```diff
--- a/src/main/java/org/bukkit/material/Sign.java
+++ b/src/main/java/org/bukkit/material/Sign.java
@@ -144,7 +144,12 @@ public class Sign extends MaterialData implements Attachable {
 
             return null;
         } else {
-            return getAttachedFace().getOppositeFace();
+            BlockFace attachedFace = getAttachedFace();
+            if (attachedFace != null) {
+                return attachedFace.getOppositeFace();
+            }
+
+            return null;
         }
     }
```

Another possible option could be for getAttachedFace() to not return null if getData() is invalid, but fallback to a reasonable replacement value.

**Comment by mastercoms** [comment]
@satoshinm Just setup the Glowkit repo with `glowkit p`.
Then, make your changes in Glowkit-Patched and then commit them. (`cd Glowkit-Patched`, `git commit -am "Patch name"`).
Finally, create a patch file from your commit using `glowkit rb`.
