### ISSUE TITLE
Error saving GlowEnderDragon in GlowChunk

### ISSUE THREAD

**Issue by awsqed** [GlowstoneMC/Glowstone#489]
Glowstone build: 2017.6.0-SNAPSHOT.a50bfef-MC1.11.2

I just afk and the error occured, 3 times.

---

```
2017/06/03 15:05:57 [INFO] Downloading sqlite-jdbc 3.15.1...
2017/06/03 15:05:57 [INFO] Downloading slf4j-jdk14 1.7.15...
2017/06/03 15:05:57 [INFO] Downloading mysql-connector-java 5.1.39...
2017/06/03 15:06:01 [INFO] Downloaded slf4j-jdk14 1.7.15.
2017/06/03 15:06:02 [INFO] Scanning plugins...
2017/06/03 15:06:02 [INFO] Created default config: config\help.yml
2017/06/03 15:06:02 [INFO] Preparing spawn for world...
2017/06/03 15:06:04 [INFO] Preparing spawn for world: 0%
2017/06/03 15:06:04 [INFO] Downloaded mysql-connector-java 5.1.39.
2017/06/03 15:06:05 [INFO] Preparing spawn for world: 2%
2017/06/03 15:06:06 [INFO] Preparing spawn for world: 4%
2017/06/03 15:06:07 [INFO] Preparing spawn for world: 12%
2017/06/03 15:06:08 [INFO] Preparing spawn for world: 22%
2017/06/03 15:06:09 [INFO] Downloaded sqlite-jdbc 3.15.1.
2017/06/03 15:06:09 [INFO] Preparing spawn for world: 33%
2017/06/03 15:06:10 [INFO] Preparing spawn for world: 44%
2017/06/03 15:06:11 [INFO] Preparing spawn for world: 55%
2017/06/03 15:06:12 [INFO] Preparing spawn for world: 66%
2017/06/03 15:06:13 [INFO] Preparing spawn for world: 81%
2017/06/03 15:06:14 [INFO] Preparing spawn for world: 98%
2017/06/03 15:06:14 [INFO] Preparing spawn for world: done
2017/06/03 15:06:14 [INFO] Preparing spawn for world_nether...
2017/06/03 15:06:16 [INFO] Preparing spawn for world_nether: 30%
2017/06/03 15:06:17 [INFO] Preparing spawn for world_nether: 69%
2017/06/03 15:06:17 [INFO] Preparing spawn for world_nether: done
2017/06/03 15:06:17 [INFO] Preparing spawn for world_the_end...
2017/06/03 15:06:18 [INFO] Preparing spawn for world_the_end: done
2017/06/03 15:06:18 [INFO] Created default config: config\commands.yml
2017/06/03 15:06:18 [INFO] Created default config: config\permissions.yml
2017/06/03 15:06:19 [INFO] Binding server to 0.0.0.0/0.0.0.0:25565...
2017/06/03 15:06:19 [INFO] Successfully bound server to 0.0.0.0/0.0.0.0:25565.
2017/06/03 15:06:19 [INFO] Ready for connections.
2017/06/03 15:06:26 [INFO] awsqed [/127.0.0.1:62571] connected, UUID: a6823d0b-6896-477c-9242-27194f8d1e0f
2017/06/03 15:06:26 [INFO] §eawsqed joined the game
2017/06/03 15:06:27 [INFO] Client brand of awsqed is: vanilla,squidhq
2017/06/03 15:11:27 [WARNING] Error saving GlowEnderDragon in GlowChunk{world=world_the_end,x=0,z=0}
java.lang.IllegalArgumentException: Unknown entity type to save: class net.glowstone.entity.monster.complex.GlowEnderDragon
	at net.glowstone.io.entity.EntityStorage.find(EntityStorage.java:168)
	at net.glowstone.io.entity.EntityStorage.save(EntityStorage.java:189)
	at net.glowstone.io.anvil.AnvilChunkIoService.write(AnvilChunkIoService.java:225)
	at net.glowstone.chunk.ChunkManager.performSave(ChunkManager.java:404)
	at net.glowstone.GlowWorld.lambda$save$7(GlowWorld.java:952)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.glowstone.scheduler.GlowTask.run(GlowTask.java:167)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2017/06/03 15:12:06 [INFO] Seed: 6661126030810129633
2017/06/03 15:13:12 [INFO] awsqed issued command: /op
2017/06/03 15:13:16 [INFO] awsqed issued command: /help
2017/06/03 15:13:24 [INFO] awsqed issued command: /pl
2017/06/03 15:13:26 [INFO] awsqed issued command: /help 2
2017/06/03 15:13:39 [INFO] CONSOLE: Opped awsqed
2017/06/03 15:13:39 [INFO] awsqed issued command: /help
2017/06/03 15:14:12 [INFO] awsqed issued command: /gc
2017/06/03 15:14:16 [INFO] awsqed issued command: /help 2
2017/06/03 15:14:20 [INFO] awsqed issued command: /glowstone
2017/06/03 15:14:36 [INFO] awsqed issued command: /help 3
2017/06/03 15:14:45 [INFO] awsqed issued command: /help 4
2017/06/03 15:14:50 [INFO] awsqed issued command: /help 5
2017/06/03 15:14:52 [INFO] awsqed issued command: /help 6
2017/06/03 15:14:56 [INFO] awsqed issued command: /help 7
2017/06/03 15:14:58 [INFO] <awsqed> a
2017/06/03 15:15:03 [INFO] awsqed issued command: /version
2017/06/03 15:16:19 [WARNING] Error saving GlowEnderDragon in GlowChunk{world=world_the_end,x=0,z=0}
java.lang.IllegalArgumentException: Unknown entity type to save: class net.glowstone.entity.monster.complex.GlowEnderDragon
	at net.glowstone.io.entity.EntityStorage.find(EntityStorage.java:168)
	at net.glowstone.io.entity.EntityStorage.save(EntityStorage.java:189)
	at net.glowstone.io.anvil.AnvilChunkIoService.write(AnvilChunkIoService.java:225)
	at net.glowstone.chunk.ChunkManager.performSave(ChunkManager.java:404)
	at net.glowstone.GlowWorld.lambda$save$7(GlowWorld.java:952)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.glowstone.scheduler.GlowTask.run(GlowTask.java:167)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2017/06/03 15:18:14 [INFO] awsqed [/127.0.0.1:62571] lost connection
2017/06/03 15:18:14 [INFO] §eawsqed left the game
2017/06/03 15:20:34 [INFO] awsqed [/127.0.0.1:63028] connected, UUID: a6823d0b-6896-477c-9242-27194f8d1e0f
2017/06/03 15:20:34 [INFO] §eawsqed joined the game
2017/06/03 15:20:34 [INFO] Client brand of awsqed is: vanilla,squidhq
2017/06/03 15:21:19 [WARNING] Error saving GlowEnderDragon in GlowChunk{world=world_the_end,x=0,z=0}
java.lang.IllegalArgumentException: Unknown entity type to save: class net.glowstone.entity.monster.complex.GlowEnderDragon
	at net.glowstone.io.entity.EntityStorage.find(EntityStorage.java:168)
	at net.glowstone.io.entity.EntityStorage.save(EntityStorage.java:189)
	at net.glowstone.io.anvil.AnvilChunkIoService.write(AnvilChunkIoService.java:225)
	at net.glowstone.chunk.ChunkManager.performSave(ChunkManager.java:404)
	at net.glowstone.GlowWorld.lambda$save$7(GlowWorld.java:952)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.glowstone.scheduler.GlowTask.run(GlowTask.java:167)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2017/06/03 15:23:47 [INFO] awsqed [/127.0.0.1:63028] lost connection
2017/06/03 15:23:49 [INFO] §eawsqed left the game
2017/06/03 15:23:50 [INFO] CONSOLE: Stopping the server..
2017/06/03 15:23:50 [INFO] The server is shutting down...
2017/06/03 15:23:51 [INFO] Saving world: world
2017/06/03 15:23:52 [INFO] Saving world: world_nether
2017/06/03 15:23:54 [INFO] Saving world: world_the_end
2017/06/03 15:23:54 [WARNING] Error saving GlowEnderDragon in GlowChunk{world=world_the_end,x=0,z=0}
java.lang.IllegalArgumentException: Unknown entity type to save: class net.glowstone.entity.monster.complex.GlowEnderDragon
	at net.glowstone.io.entity.EntityStorage.find(EntityStorage.java:168)
	at net.glowstone.io.entity.EntityStorage.save(EntityStorage.java:189)
	at net.glowstone.io.anvil.AnvilChunkIoService.write(AnvilChunkIoService.java:225)
	at net.glowstone.chunk.ChunkManager.performSave(ChunkManager.java:404)
	at net.glowstone.GlowWorld.lambda$save$7(GlowWorld.java:952)
	at net.glowstone.GlowWorld.maybeAsync(GlowWorld.java:1688)
	at net.glowstone.GlowWorld.save(GlowWorld.java:950)
	at net.glowstone.GlowServer.unloadWorld(GlowServer.java:1683)
	at net.glowstone.GlowServer.shutdown(GlowServer.java:767)
	at org.bukkit.Bukkit.shutdown(Bukkit.java:713)
	at org.bukkit.command.defaults.StopCommand.execute(StopCommand.java:26)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188)
	at net.glowstone.GlowServer.dispatchCommand(GlowServer.java:1362)
	at net.glowstone.ConsoleManager$CommandTask.run(ConsoleManager.java:284)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.glowstone.scheduler.GlowTask.run(GlowTask.java:167)
	at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:152)
	at net.glowstone.scheduler.GlowScheduler.lambda$start$0(GlowScheduler.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by aramperes** [comment]
Looks like EntityStorage for `GlowEnderDragon` isn't implemented. (cc @mastercoms)

**Comment by mastercoms** [comment]
Yep, `GlowEnderDragon` is a rather lazy implementation.
