### ISSUE TITLE
Server fails to start after initial worldgen, NPE at net.glowstone.GlowWorld.prepareSpawn(GlowWorld.java:796)

### ISSUE THREAD

**Issue by satoshinm** [GlowstoneMC/Glowstone#490]
Since build 538 with, Glowstone server is able to generate a fresh initial world but subsequent invocations fail with a null pointer exception and stop the server. If I revert https://github.com/GlowstoneMC/Glowstone/commit/f5abedc5d720dbd4c6f3cb8e1a1a711516e0fa69 I am able to start the server successfully. Full console log:

```
tmp $ java -jar /Users/admin/Downloads/glowstone.jar 
23:37:07 [INFO] This server is running Glowstone version 2017.6.0-SNAPSHOT.f5abedc-MC1.11.2 (Implementing API version 1.11.2-R0.1-SNAPSHOT)
23:37:07 [INFO] Creating default config: config/glowstone.yml
23:37:07 [INFO] Creating default world config: config/worlds.yml
23:37:07 [INFO] Recipes: 299 shaped, 63 shapeless, 26 furnace, 10 dynamic, 28 fuels.
23:37:07 [INFO] Downloading sqlite-jdbc 3.15.1...
23:37:07 [INFO] Downloading slf4j-jdk14 1.7.15...
23:37:07 [INFO] Downloading mysql-connector-java 5.1.39...
23:37:10 [INFO] Downloaded slf4j-jdk14 1.7.15.
23:37:10 [INFO] Downloaded mysql-connector-java 5.1.39.
23:37:10 [INFO] Downloaded sqlite-jdbc 3.15.1.
23:37:10 [INFO] Scanning plugins...
23:37:10 [INFO] Created default config: config/help.yml
23:37:10 [INFO] Preparing spawn for world...
23:37:12 [INFO] Preparing spawn for world: 0%
23:37:13 [INFO] Preparing spawn for world: 3%
23:37:14 [INFO] Preparing spawn for world: 10%
23:37:15 [INFO] Preparing spawn for world: 24%
23:37:16 [INFO] Preparing spawn for world: 38%
23:37:17 [INFO] Preparing spawn for world: 52%
23:37:18 [INFO] Preparing spawn for world: 70%
23:37:19 [INFO] Preparing spawn for world: 92%
23:37:19 [INFO] Preparing spawn for world: done
23:37:19 [INFO] Preparing spawn for world_nether...
23:37:20 [INFO] Preparing spawn for world_nether: 43%
23:37:21 [INFO] Preparing spawn for world_nether: done
23:37:21 [INFO] Preparing spawn for world_the_end...
23:37:22 [INFO] Preparing spawn for world_the_end: done
23:37:22 [INFO] Created default config: config/commands.yml
23:37:22 [INFO] Created default config: config/permissions.yml
23:37:22 [INFO] Binding server to 0.0.0.0/0.0.0.0:25565...
23:37:22 [INFO] Successfully bound server to 0.0.0.0/0.0.0.0:25565.
23:37:22 [INFO] Ready for connections.
>stop
23:37:24 [INFO] CONSOLE: Stopping the server..
23:37:24 [INFO] The server is shutting down...
23:37:24 [INFO] Saving world: world
23:37:25 [INFO] Saving world: world_nether
23:37:26 [INFO] Saving world: world_the_end
>tmp $ java -jar /Users/admin/Downloads/glowstone.jar 
23:37:29 [INFO] This server is running Glowstone version 2017.6.0-SNAPSHOT.f5abedc-MC1.11.2 (Implementing API version 1.11.2-R0.1-SNAPSHOT)
23:37:29 [INFO] Recipes: 299 shaped, 63 shapeless, 26 furnace, 10 dynamic, 28 fuels.
23:37:29 [INFO] Scanning plugins...
23:37:29 [SEVERE] Error during server startup.
java.lang.NullPointerException
	at net.glowstone.GlowWorld.prepareSpawn(GlowWorld.java:796)
	at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:764)
	at net.glowstone.GlowWorld.setSpawnLocation(GlowWorld.java:728)
	at net.glowstone.GlowWorld.setSpawnLocation(GlowWorld.java:717)
	at net.glowstone.io.nbt.NbtWorldMetadataService.readWorldData(NbtWorldMetadataService.java:107)
	at net.glowstone.GlowWorld.<init>(GlowWorld.java:300)
	at net.glowstone.GlowServer.createWorld(GlowServer.java:1657)
	at net.glowstone.GlowServer.start(GlowServer.java:619)
	at net.glowstone.GlowServer.run(GlowServer.java:452)
	at net.glowstone.GlowServer.main(GlowServer.java:322)
```

**Comment by satoshinm** [comment]
The NPE is occurring here:

```java
             for (int z = centerZ - radius; z <= centerZ + radius; ++z) {
                 ++current;
                 if (populateAnchoredChunks) {
                    getChunkManager().forcePopulation(x, z);
```

but if I add a null check:

```java
                    ChunkManager chunkManager = getChunkManager();
                    if (chunkManager != null) {
                        getChunkManager().forcePopulation(x, z);
                    }
```

then it crashes later (the fix may be more complicated):

```
09:13:00 [SEVERE] Error during server startup.
java.lang.NullPointerException
	at net.glowstone.chunk.ChunkManager.access$200(ChunkManager.java:33)
	at net.glowstone.chunk.ChunkManager$ChunkLock.acquire(ChunkManager.java:457)
	at net.glowstone.GlowWorld.prepareSpawn(GlowWorld.java:803)
	at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:764)
	at net.glowstone.GlowWorld.setSpawnLocation(GlowWorld.java:728)
	at net.glowstone.GlowWorld.setSpawnLocation(GlowWorld.java:717)
	at net.glowstone.io.nbt.NbtWorldMetadataService.readWorldData(NbtWorldMetadataService.java:107)
	at net.glowstone.GlowWorld.<init>(GlowWorld.java:300)
	at net.glowstone.GlowServer.createWorld(GlowServer.java:1657)
	at net.glowstone.GlowServer.start(GlowServer.java:619)
	at net.glowstone.GlowServer.run(GlowServer.java:452)
	at net.glowstone.GlowServer.main(GlowServer.java:322)
```
