### ISSUE TITLE
Mixed worlds in dev

### ISSUE THREAD

**Issue by Pr0methean** [GlowstoneMC/Glowstone#630]
Glowstone build: dev at a822f0c9d79badf5c89ce1c877456841117deadf

After entering a world, stopping and restarting the server, I get many warnings similar to the one below. When I enter the world again, it contains a mix of overworld, end and nether chunks!

02:41:01 [WARNING] Error loading entity in GlowChunk{world=world_nether,x=-6,z=0}: minecraft:ender_crystal
java.lang.IllegalArgumentException: Entity in wrong world: stored in GlowWorld(name=world_nether) but data says GlowWorld(name=world)
        at net.glowstone.io.entity.EntityStorage.loadEntity(EntityStorage.java:159)
        at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:106)
        at net.glowstone.chunk.ChunkManager.loadChunk(ChunkManager.java:150)
        at net.glowstone.chunk.ChunkManager.loadChunk(ChunkManager.java:144)
        at net.glowstone.chunk.ChunkManager.populateChunk(ChunkManager.java:217)
        at net.glowstone.chunk.ChunkManager.forcePopulation(ChunkManager.java:249)
        at net.glowstone.GlowWorld.prepareSpawn(GlowWorld.java:895)
        at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:868)
        at net.glowstone.GlowWorld.<init>(GlowWorld.java:393)
        at net.glowstone.GlowServer.createWorld(GlowServer.java:1861)
        at net.glowstone.GlowServer.start(GlowServer.java:720)
        at net.glowstone.GlowServer.run(GlowServer.java:560)
        at net.glowstone.GlowServer.main(GlowServer.java:427)

**Comment by Pr0methean** [comment]
![2017-12-20_02 56 59](https://user-images.githubusercontent.com/4961925/34203944-a9da1674-e531-11e7-9052-b03b3e076c25.png)

**Comment by Pr0methean** [comment]
[world.zip](https://github.com/GlowstoneMC/Glowstone/files/1575401/world.zip)

**Comment by Pr0methean** [comment]
With #628 at 899705d, this only seems to happen to nether chunks and not end chunks.

**Comment by Pr0methean** [comment]
Update: This seems to depend not on PR #628, but on how many chunks are generated the first time the server is run for the world.
