### ISSUE TITLE
macOS: KQueue event loop is incompatible

### ISSUE THREAD

**Issue by XuZhen86** [GlowstoneMC/Glowstone#850]
Steps to recreate:
1. Launch server and client.
2. Client login.
3. Server generates error message and kicks the client.

The following is the complete log:
```
11:59:11 [INFO] This server is running Glowstone version 2018.2.0-SNAPSHOT.e92d159 (MC: 1.12.2) (Implementing API version 1.12.2-R2.0-SNAPSHOT)
11:59:11 [INFO] Recipes: 307 shaped, 63 shapeless, 26 furnace, 10 dynamic, 44 fuels.
11:59:11 [INFO] Scanning plugins...
11:59:11 [INFO] Preparing spawn for world...
11:59:12 [INFO] Preparing spawn for world: done
11:59:12 [INFO] Preparing spawn for world_nether...
11:59:12 [INFO] Preparing spawn for world_nether: done
11:59:12 [INFO] Preparing spawn for world_the_end...
11:59:13 [INFO] Preparing spawn for world_the_end: done
11:59:13 [INFO] Native kqueue transport is enabled.
11:59:13 [INFO] Binding server to 0.0.0.0:25565...
11:59:13 [INFO] Successfully bound server to 0.0.0.0:25565.
11:59:13 [INFO] Ready for connections.
11:59:23 [SEVERE] Error in authentication thread
java.lang.IllegalStateException: incompatible event loop type: io.netty.channel.kqueue.KQueueEventLoop
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:469)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
        at net.glowstone.net.http.HttpClient.connect(HttpClient.java:79)
        at net.glowstone.net.handler.login.EncryptionKeyResponseHandler.handle(EncryptionKeyResponseHandler.java:120)
        at net.glowstone.net.handler.login.EncryptionKeyResponseHandler.handle(EncryptionKeyResponseHandler.java:36)
        at com.flowpowered.network.session.BasicSession.handleMessage(BasicSession.java:80)
        at com.flowpowered.network.session.BasicSession.messageReceived(BasicSession.java:136)
        at net.glowstone.net.GlowSession.messageReceived(GlowSession.java:534)
        at net.glowstone.net.pipeline.MessageHandler.channelRead0(MessageHandler.java:50)
        at net.glowstone.net.pipeline.MessageHandler.channelRead0(MessageHandler.java:15)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
        at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:543)
        at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:402)
        at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:195)
        at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:269)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
11:59:23 [INFO] [/127.0.0.1:61871] kicked: Internal error during authentication.
```

System information:
1. Java version:
```
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
```
2. System Software Overview:
```
  System Version:	macOS 10.12.6 (16G1212)
  Kernel Version:	Darwin 16.7.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	*
  User Name:	*
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	1 day 19:21
```

**Comment by aramperes** [comment]
Is this line logged during startup, before binding the server?

```
Native kqueue transport is enabled.
```

**Comment by XuZhen86** [comment]
The complete log:
```
11:59:11 [INFO] This server is running Glowstone version 2018.2.0-SNAPSHOT.e92d159 (MC: 1.12.2) (Implementing API version 1.12.2-R2.0-SNAPSHOT)
11:59:11 [INFO] Recipes: 307 shaped, 63 shapeless, 26 furnace, 10 dynamic, 44 fuels.
11:59:11 [INFO] Scanning plugins...
11:59:11 [INFO] Preparing spawn for world...
11:59:12 [INFO] Preparing spawn for world: done
11:59:12 [INFO] Preparing spawn for world_nether...
11:59:12 [INFO] Preparing spawn for world_nether: done
11:59:12 [INFO] Preparing spawn for world_the_end...
11:59:13 [INFO] Preparing spawn for world_the_end: done
11:59:13 [INFO] Native kqueue transport is enabled.
11:59:13 [INFO] Binding server to 0.0.0.0:25565...
11:59:13 [INFO] Successfully bound server to 0.0.0.0:25565.
11:59:13 [INFO] Ready for connections.
11:59:23 [SEVERE] Error in authentication thread
java.lang.IllegalStateException: incompatible event loop type: io.netty.channel.kqueue.KQueueEventLoop
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:469)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
        at net.glowstone.net.http.HttpClient.connect(HttpClient.java:79)
        at net.glowstone.net.handler.login.EncryptionKeyResponseHandler.handle(EncryptionKeyResponseHandler.java:120)
        at net.glowstone.net.handler.login.EncryptionKeyResponseHandler.handle(EncryptionKeyResponseHandler.java:36)
        at com.flowpowered.network.session.BasicSession.handleMessage(BasicSession.java:80)
        at com.flowpowered.network.session.BasicSession.messageReceived(BasicSession.java:136)
        at net.glowstone.net.GlowSession.messageReceived(GlowSession.java:534)
        at net.glowstone.net.pipeline.MessageHandler.channelRead0(MessageHandler.java:50)
        at net.glowstone.net.pipeline.MessageHandler.channelRead0(MessageHandler.java:15)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
        at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:543)
        at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:402)
        at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:195)
        at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:269)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
11:59:23 [INFO] [/127.0.0.1:61871] kicked: Internal error during authentication.
>
```

**Comment by mastercoms** [comment]
See https://github.com/GlowstoneMC/Glowstone/commit/5fb3b08ac5f06b8853623d65b60317ff7b4c1133 for a possible fix.

**Comment by XuZhen86** [comment]
```
13:12:40 [INFO] This server is running Glowstone version 2018.2.0-SNAPSHOT.5fb3b08 (MC: 1.12.2) (Implementing API version 1.12.2-R2.0-SNAPSHOT)
13:12:40 [INFO] Recipes: 307 shaped, 63 shapeless, 26 furnace, 10 dynamic, 44 fuels.
13:12:41 [INFO] Scanning plugins...
13:12:41 [INFO] Preparing spawn for world...
13:12:41 [INFO] Preparing spawn for world: done
13:12:41 [INFO] Preparing spawn for world_nether...
13:12:42 [INFO] Preparing spawn for world_nether: done
13:12:42 [INFO] Preparing spawn for world_the_end...
13:12:42 [INFO] Preparing spawn for world_the_end: done
13:12:42 [INFO] Native kqueue transport is enabled.
13:12:42 [INFO] Binding server to 0.0.0.0:25565...
13:12:42 [INFO] Successfully bound server to 0.0.0.0:25565.
13:12:42 [INFO] Ready for connections.
13:12:46 [SEVERE] Error in authentication thread
java.lang.IllegalStateException: incompatible event loop type: io.netty.channel.kqueue.KQueueEventLoop
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:469)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
        at net.glowstone.net.http.HttpClient.connect(HttpClient.java:82)
        at net.glowstone.net.handler.login.EncryptionKeyResponseHandler.handle(EncryptionKeyResponseHandler.java:120)
        at net.glowstone.net.handler.login.EncryptionKeyResponseHandler.handle(EncryptionKeyResponseHandler.java:36)
        at com.flowpowered.network.session.BasicSession.handleMessage(BasicSession.java:80)
        at com.flowpowered.network.session.BasicSession.messageReceived(BasicSession.java:136)
        at net.glowstone.net.GlowSession.messageReceived(GlowSession.java:534)
        at net.glowstone.net.pipeline.MessageHandler.channelRead0(MessageHandler.java:50)
        at net.glowstone.net.pipeline.MessageHandler.channelRead0(MessageHandler.java:15)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
        at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:543)
        at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:402)
        at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:195)
        at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:269)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
13:12:46 [INFO] [/127.0.0.1:62629] kicked: Internal error during authentication.
```

**Comment by mastercoms** [comment]
It should work now. https://github.com/GlowstoneMC/Glowstone/commit/063a5d0b66d2a339a457fdcb6211dfa66278eb1f.

**Comment by XuZhen86** [comment]
It works!
