### ISSUE TITLE
NPE when trying to load EntityHorse

### ISSUE THREAD

**Issue by Postremus** [GlowstoneMC/Glowstone#86]
Hey,

we started today to play around with g++. We imported our old survival world. Got this exception on startup. Could it be that Entitys are not fully implemented yet? What is the current state of them?

```
2015/08/11 22:16:22 [WARNUNG] Error loading entity in GlowChunk{world=world,x=-25,z=22}: EntityHorse
java.lang.NullPointerException
    at net.glowstone.entity.passive.GlowHorse.<init>(GlowHorse.java:40)
    at net.glowstone.entity.passive.GlowHorse.<init>(GlowHorse.java:35)
    at net.glowstone.io.entity.HorseStore.createEntity(HorseStore.java:38)
    at net.glowstone.io.entity.HorseStore.createEntity(HorseStore.java:16)
    at net.glowstone.io.entity.EntityStorage.createEntity(EntityStorage.java:101)
    at net.glowstone.io.entity.EntityStorage.loadEntity(EntityStorage.java:94)
    at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:108)
    at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:131)
    at net.glowstone.GlowChunk.load(GlowChunk.java:265)
    at net.glowstone.GlowChunk.load(GlowChunk.java:260)
    at net.glowstone.GlowWorld.loadChunk(GlowWorld.java:1078)
    at net.glowstone.GlowWorld.setKeepSpawnInMemory(GlowWorld.java:735)
    at net.glowstone.GlowWorld.<init>(GlowWorld.java:345)
    at net.glowstone.GlowServer.createWorld(GlowServer.java:1425)
    at net.glowstone.GlowServer.start(GlowServer.java:483)
    at net.glowstone.GlowServer.main(GlowServer.java:111)
```

Greetings
Postremus

**Comment by Postremus** [comment]
Also got this error while saving horses:
```
2015/08/11 22:20:48 [WARNUNG] Error saving GlowHorse in GlowChunk{world=world,x=3,z=13}
java.lang.NullPointerException
	at net.glowstone.io.entity.HorseStore.save(HorseStore.java:81)
	at net.glowstone.io.entity.HorseStore.save(HorseStore.java:16)
	at net.glowstone.io.entity.EntityStorage.save(EntityStorage.java:136)
	at net.glowstone.io.anvil.AnvilChunkIoService.write(AnvilChunkIoService.java:212)
	at net.glowstone.ChunkManager.performSave(ChunkManager.java:377)
	at net.glowstone.GlowWorld$1.run(GlowWorld.java:919)
	at net.glowstone.GlowWorld.maybeAsync(GlowWorld.java:1599)
	at net.glowstone.GlowWorld.save(GlowWorld.java:915)
	at net.glowstone.GlowServer.unloadWorld(GlowServer.java:1450)
	at net.glowstone.GlowServer.shutdown(GlowServer.java:647)
	at org.bukkit.Bukkit.shutdown(Bukkit.java:710)
	at org.bukkit.command.defaults.StopCommand.execute(StopCommand.java:28)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:184)
	at net.glowstone.GlowServer.dispatchCommand(GlowServer.java:1145)
	at net.glowstone.entity.GlowPlayer$2.run(GlowPlayer.java:1557)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at net.glowstone.scheduler.GlowTask.run(GlowTask.java:163)
	at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:181)
	at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
	at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:110)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mastercoms** [comment]
Very basic entity support is included in Glowstone++. The representations and some mechanics of passive creatures are added, but nothing that can be have entities in the world yet. Though, this is being worked on, and is one of the big things we're trying to touch on in our first versioned release.

**Comment by Postremus** [comment]
In which issue is the state of entities tracked?

----- Ursprüngliche Nachricht -----
Von: "mastercoms" <notifications@github.com>
Gesendet: ‎12.‎08.‎2015 22:13
An: "GlowstonePlusPlus/GlowstonePlusPlus" <GlowstonePlusPlus@noreply.github.com>
Cc: "Martin Panzer" <postremus1996@googlemail.com>
Betreff: Re: [GlowstonePlusPlus] NPE when trying to load EntityHorse (#86)

Closed #86.

**Comment by mastercoms** [comment]
There isn't an issue where the entities are tracked, but the entities PR is listed in here: https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/issues/55

**Comment by Postremus** [comment]
any way to get the entities PR merged faster?

**Comment by mastercoms** [comment]
Well there are a lot of merge conflicts with it, but I am planning to merge it this weekend.

**Comment by mastercoms** [comment]
Here it is: https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/pull/91
