### ISSUE TITLE
Server crashes on startup, MissingResourceException

### ISSUE THREAD

**Issue by XuZhen86** [GlowstoneMC/Glowstone#885]
Steps to recreate:

```mvn clean```
```mvn package```
Copy glowstone.jar to an empty directory
Launch server

Log:
```
09:47:47 [INFO] This server is running Glowstone version 2018.3.0-SNAPSHOT.363916c (MC: 1.12.2) (Implementing API version 1.12.2-R2.1-SNAPSHOT)
09:47:47 [INFO] Recipes: 307 shaped, 63 shapeless, 26 furnace, 10 dynamic, 44 fuels.
09:47:48 [INFO] Scanning plugins...
09:47:48 [INFO] Preparing spawn for world...
09:47:49 [INFO] Preparing spawn for world: 0%
09:47:51 [INFO] Preparing spawn for world: 2%
09:47:52 [INFO] Preparing spawn for world: 4%
09:47:53 [INFO] Preparing spawn for world: 15%
09:47:54 [INFO] Preparing spawn for world: 28%
09:47:55 [INFO] Preparing spawn for world: 41%
09:47:56 [INFO] Preparing spawn for world: 60%
09:47:57 [INFO] Preparing spawn for world: 76%
09:47:58 [INFO] Preparing spawn for world: 95%
09:47:58 [INFO] Preparing spawn for world: done
09:47:58 [INFO] Preparing spawn for world_nether...
09:47:59 [INFO] Preparing spawn for world_nether: 39%
09:48:00 [INFO] Preparing spawn for world_nether: 97%
09:48:00 [INFO] Preparing spawn for world_nether: done
09:48:00 [INFO] Preparing spawn for world_the_end...
09:48:01 [INFO] Preparing spawn for world_the_end: done
09:48:01 [INFO] Native kqueue transport is enabled.
09:48:01 [INFO] Binding server to 0.0.0.0:25565...
09:48:02 [INFO] Successfully bound server to 0.0.0.0:25565.
09:48:02 [SEVERE] Error during server startup.
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key console.info.ready
        at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
        at java.util.ResourceBundle.getString(ResourceBundle.java:407)
        at net.glowstone.GlowServer.run(GlowServer.java:616)
        at net.glowstone.GlowServer.main(GlowServer.java:480)
> The terminal process terminated with exit code: 1
```

Java version:
```
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
```
System Software Overview:
```
  System Version:	macOS 10.12.6 (16G1212)
  Kernel Version:	Darwin 16.7.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	*
  User Name:	*
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	8 days 13:35
```

**Comment by Pr0methean** [comment]
If the resource file were missing from the jar, the message "Error during server startup" wouldn't be available either, so clearly the resource file is present.

**Comment by Pr0methean** [comment]
Found the cause: that one string disappeared while I was sorting the resource file alphabetically.
