### ISSUE TITLE
Crashes on my server that previously ran Spigot 1.8.8

### ISSUE THREAD

**Issue by Pocketkid2** [GlowstoneMC/Glowstone#94]
I have a server where I play with some plugins, including WorldEdit, WorldGuard, and Movecraft. I wanted to see if replacing the Spigot with GlowstonePlusPlus would have a performance enhancement.

It appears to work pretty fast! Although there are a lot of issues, and I will list the ones I noticed.
- Pasting in WE schematics was terrible (signs had no data, and later on a bigger schematics, all blocks with a lot of data were not pasted, like redstone, doors, trapdoors, ladders, signs, levers, everything like that)
- When I right clicked things like signs I got WorldGuard PlayerInteractEvent crashes in the console (see log)
- Moving the ship gave a ton of warnings in the console (see log)

Here is the entire crash log for my server, including plugin startup http://pastebin.com/3K9JgfQK
##

**Comment by gdude2002** [comment]
Something a lot of people seem to miss is that Glowstone++ (and base Glowstone) isn't production-ready yet. That said..

```
2015/09/11 09:26:49 [WARNING] [WorldEdit]
**********************************************
** This WorldEdit version does not fully support your version of Bukkit.
**
** When working with blocks or undoing, chests will be empty, signs
** will be blank, and so on. There will be no support for entity
** and biome-related functions.
**
** Please see http://wiki.sk89q.com/wiki/WorldEdit/Bukkit_adapters
**********************************************
```

Naturally, WorldEdit doesn't have explicit support for Glowstone, so this is expected.

```
2015/09/11 11:21:48 [SEVERE] [Movecraft] Error while executing GlowTask{id=375, plugin=Movecraft v4.0.1, sync=true: net.countercraft.movecraft.utils.MapUpdateManager$1@19c3665f}
java.lang.StackOverflowError
        at net.glowstone.GlowWorld.getChunkAt(GlowWorld.java:992)
        at net.glowstone.GlowWorld.getBlockAt(GlowWorld.java:977)
        at net.glowstone.block.GlowBlock.getRelative(GlowBlock.java:172)
        at net.glowstone.block.GlowBlock.getRelative(GlowBlock.java:177)
        at net.glowstone.block.blocktype.BlockRedstone.calculateConnections(BlockRedstone.java:226)
        at net.glowstone.block.blocktype.BlockRedstone.extraUpdate(BlockRedstone.java:193)
        at net.glowstone.block.blocktype.BlockRedstone.updatePhysics(BlockRedstone.java:186)
        at net.glowstone.block.blocktype.BlockRedstone.onNearBlockChanged(BlockRedstone.java:65)
        at net.glowstone.block.blocktype.BlockRedstone.extraUpdate(BlockRedstone.java:201)
        at net.glowstone.block.blocktype.BlockRedstone.updatePhysics(BlockRedstone.java:186)
        at net.glowstone.block.blocktype.BlockRedstone.onNearBlockChanged(BlockRedstone.java:65)
        at net.glowstone.block.blocktype.BlockRedstone.extraUpdate(BlockRedstone.java:201)
        at net.glowstone.block.blocktype.BlockRedstone.updatePhysics(BlockRedstone.java:186)
        at net.glowstone.block.blocktype.BlockRedstone.onNearBlockChanged(BlockRedstone.java:65)
        at net.glowstone.block.blocktype.BlockRedstone.extraUpdate(BlockRedstone.java:201)
        at net.glowstone.block.blocktype.BlockRedstone.updatePhysics(BlockRedstone.java:186)
        at net.glowstone.block.blocktype.BlockRedstone.onNearBlockChanged(BlockRedstone.java:65)
        at net.glowstone.block.blocktype.BlockRedstone.extraUpdate(BlockRedstone.java:201)
        at net.glowstone.block.blocktype.BlockRedstone.updatePhysics(BlockRedstone.java:186)
        at net.glowstone.block.blocktype.BlockRedstone.onNearBlockChanged(BlockRedstone.java:65)
        at net.glowstone.block.blocktype.BlockRedstone.extraUpdate(BlockRedstone.java:201)
        at net.glowstone.block.blocktype.BlockRedstone.updatePhysics(BlockRedstone.java:186)
        at net.glowstone.block.blocktype.BlockRedstone.onNearBlockChanged(BlockRedstone.java:65)
        
        [...]

        at net.glowstone.block.blocktype.BlockRedstone.updatePhysics(BlockRedstone.java:186)
```

This looks like an infinite loop in the redstone logic. Did your ship have a lot of redstone on it? @mastercoms - Who is in charge of redstone?

**Comment by Pocketkid2** [comment]
I am fully aware that this is not ready for main use. I should have mentioned that I was only testing these plugins to judge if GlowstonePlusPlus was giving better performance and if it would currently work as is. I also had hope that the errors I have provided would give the dev team help in fixing bugs.

**Comment by mastercoms** [comment]
We can't do anything about WorldEdit for Bukkit, it uses Mojang code to do the chest and sign stuff. Hopefully, the Sponge version uses the API and not internal code plugin developers shouldn't be using. In that case, we will be able to support the WorldEdit for Sponge plugin once Bukkit2Sponge is further along.

I'll see what I can do for the PlayerInteractEvent bug:
```java
[SEVERE] Could not pass event PlayerInteractEvent to WorldGuard v6.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:532)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:517)
        at net.glowstone.EventFactory$1.run(EventFactory.java:47)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at net.glowstone.scheduler.GlowScheduler.scheduleInTickExecution(GlowScheduler.java:155)
        at net.glowstone.EventFactory.callEvent(EventFactory.java:50)
        at net.glowstone.EventFactory.onPlayerInteract(EventFactory.java:156)
        at net.glowstone.net.handler.play.player.BlockPlacementHandler.handle(BlockPlacementHandler.java:95)
        at net.glowstone.net.handler.play.player.BlockPlacementHandler.handle(BlockPlacementHandler.java:23)
        at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
        at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
        at net.glowstone.net.GlowSession.pulse(GlowSession.java:430)
        at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:173)
        at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
        at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:110)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.handleBlockRightClick(WorldGuardPlayerListener.java:257)
        at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerInteract(WorldGuardPlayerListener.java:194)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
        ... 25 more
```

@SamNosliw is in charge of redstone, he made it.

**Comment by Pocketkid2** [comment]
Thanks a lot! Keep me posted!

**Comment by mastercoms** [comment]
I've noticed Essentials also throws errors for PlayerDamageEvent or something, so maybe our Player events are botched?

**Comment by mastercoms** [comment]
Released a possible fix for interact event: https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/1dee3499bc66ec66701cb3a595af83c3a0f54d0d

**Comment by mastercoms** [comment]
@Pocketkid2 Could you test to see which issues are still there? I'm pretty sure the Essentials error is fixed and maybe the Movecraft error has been as well.

**Comment by gdude2002** [comment]
This is a fairly old ticket; can someone test this before I close it?

**Comment by mastercoms** [comment]
I think we should split this issue. Everything is solved except the redstone bug.
