### ISSUE TITLE
error when tnt explodes

### ISSUE THREAD

**Issue by nerlu** [GlowstoneMC/Glowstone#96]
this exception is spamed multiple times after one tnt is exploded.
The exploding tnt sound is also hearable multiple times

```
19:47:28 [SCHWERWIEGEND] Error occurred while pulsing world world
java.lang.NullPointerException
        at net.glowstone.Explosion.calculateEnchantedDamage(Explosion.java:272)
        at net.glowstone.Explosion.damageEntities(Explosion.java:252)
        at net.glowstone.Explosion.explodeWithEvent(Explosion.java:109)
        at net.glowstone.GlowWorld.createExplosion(GlowWorld.java:1462)
        at net.glowstone.entity.GlowTNTPrimed.explode(GlowTNTPrimed.java:55)
        at net.glowstone.entity.GlowTNTPrimed.pulse(GlowTNTPrimed.java:43)
        at net.glowstone.GlowWorld.pulse(GlowWorld.java:414)
        at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:48)
```

**Comment by mastercoms** [comment]
This is with the latest build, right?

**Comment by Postremus** [comment]
yes

**Comment by Luki110998** [comment]
Yes
